// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: courses.sql

package sqlc

import (
	"context"

	"github.com/google/uuid"
)

const createCourse = `-- name: CreateCourse :one
INSERT INTO courses (
    tenant_id,
    name
) VALUES (
    $1, $2
) RETURNING id, tenant_id, name
`

type CreateCourseParams struct {
	TenantID uuid.UUID `json:"tenant_id"`
	Name     string    `json:"name"`
}

func (q *Queries) CreateCourse(ctx context.Context, arg CreateCourseParams) (Course, error) {
	row := q.db.QueryRow(ctx, createCourse, arg.TenantID, arg.Name)
	var i Course
	err := row.Scan(&i.ID, &i.TenantID, &i.Name)
	return i, err
}

const getCourse = `-- name: GetCourse :one
SELECT id, tenant_id, name FROM courses
WHERE id = $1 AND tenant_id = $2
`

type GetCourseParams struct {
	ID       uuid.UUID `json:"id"`
	TenantID uuid.UUID `json:"tenant_id"`
}

func (q *Queries) GetCourse(ctx context.Context, arg GetCourseParams) (Course, error) {
	row := q.db.QueryRow(ctx, getCourse, arg.ID, arg.TenantID)
	var i Course
	err := row.Scan(&i.ID, &i.TenantID, &i.Name)
	return i, err
}

const listCourses = `-- name: ListCourses :many
SELECT id, tenant_id, name FROM courses
WHERE tenant_id = $1
ORDER BY name
`

func (q *Queries) ListCourses(ctx context.Context, tenantID uuid.UUID) ([]Course, error) {
	rows, err := q.db.Query(ctx, listCourses, tenantID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Course{}
	for rows.Next() {
		var i Course
		if err := rows.Scan(&i.ID, &i.TenantID, &i.Name); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
