// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: courses.sql

package sqlc

import (
	"context"

	"github.com/google/uuid"
)

const createCourse = `-- name: CreateCourse :one
INSERT INTO courses (
    tenant_id,
    name
) VALUES (
    $1, $2
) RETURNING id, tenant_id, name
`

type CreateCourseParams struct {
	TenantID uuid.UUID `json:"tenant_id"`
	Name     string    `json:"name"`
}

func (q *Queries) CreateCourse(ctx context.Context, arg CreateCourseParams) (Course, error) {
	row := q.db.QueryRow(ctx, createCourse, arg.TenantID, arg.Name)
	var i Course
	err := row.Scan(&i.ID, &i.TenantID, &i.Name)
	return i, err
}

const deleteCourse = `-- name: DeleteCourse :exec
DELETE FROM courses
WHERE id = $1 AND tenant_id = $2
`

type DeleteCourseParams struct {
	ID       int32     `json:"id"`
	TenantID uuid.UUID `json:"tenant_id"`
}

func (q *Queries) DeleteCourse(ctx context.Context, arg DeleteCourseParams) error {
	_, err := q.db.Exec(ctx, deleteCourse, arg.ID, arg.TenantID)
	return err
}

const getCourse = `-- name: GetCourse :one
SELECT id, tenant_id, name FROM courses
WHERE id = $1 AND tenant_id = $2
`

type GetCourseParams struct {
	ID       int32     `json:"id"`
	TenantID uuid.UUID `json:"tenant_id"`
}

func (q *Queries) GetCourse(ctx context.Context, arg GetCourseParams) (Course, error) {
	row := q.db.QueryRow(ctx, getCourse, arg.ID, arg.TenantID)
	var i Course
	err := row.Scan(&i.ID, &i.TenantID, &i.Name)
	return i, err
}

const getCourseByName = `-- name: GetCourseByName :one
SELECT id, tenant_id, name FROM courses
WHERE name = $1 AND tenant_id = $2
`

type GetCourseByNameParams struct {
	Name     string    `json:"name"`
	TenantID uuid.UUID `json:"tenant_id"`
}

func (q *Queries) GetCourseByName(ctx context.Context, arg GetCourseByNameParams) (Course, error) {
	row := q.db.QueryRow(ctx, getCourseByName, arg.Name, arg.TenantID)
	var i Course
	err := row.Scan(&i.ID, &i.TenantID, &i.Name)
	return i, err
}

const listCourses = `-- name: ListCourses :many
SELECT id, tenant_id, name FROM courses
WHERE tenant_id = $1
ORDER BY name
`

func (q *Queries) ListCourses(ctx context.Context, tenantID uuid.UUID) ([]Course, error) {
	rows, err := q.db.Query(ctx, listCourses, tenantID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Course{}
	for rows.Next() {
		var i Course
		if err := rows.Scan(&i.ID, &i.TenantID, &i.Name); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateCourse = `-- name: UpdateCourse :one
UPDATE courses
SET name = $3
WHERE id = $1 AND tenant_id = $2
RETURNING id, tenant_id, name
`

type UpdateCourseParams struct {
	ID       int32     `json:"id"`
	TenantID uuid.UUID `json:"tenant_id"`
	Name     string    `json:"name"`
}

func (q *Queries) UpdateCourse(ctx context.Context, arg UpdateCourseParams) (Course, error) {
	row := q.db.QueryRow(ctx, updateCourse, arg.ID, arg.TenantID, arg.Name)
	var i Course
	err := row.Scan(&i.ID, &i.TenantID, &i.Name)
	return i, err
}
