// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: holes.sql

package sqlc

import (
	"context"

	"github.com/google/uuid"
)

const createHole = `-- name: CreateHole :one
INSERT INTO holes (
    course_id,
    tee_color_id,
    number,
    tenant_id,
    par,
    hdcp,
    yards
) VALUES (
    $1, $2, $3, $4, $5, $6, $7
) RETURNING course_id, tee_color_id, number, tenant_id, par, hdcp, yards
`

type CreateHoleParams struct {
	CourseID   int32     `json:"course_id"`
	TeeColorID int32     `json:"tee_color_id"`
	Number     int32     `json:"number"`
	TenantID   uuid.UUID `json:"tenant_id"`
	Par        int32     `json:"par"`
	Hdcp       int32     `json:"hdcp"`
	Yards      int32     `json:"yards"`
}

func (q *Queries) CreateHole(ctx context.Context, arg CreateHoleParams) (Hole, error) {
	row := q.db.QueryRow(ctx, createHole,
		arg.CourseID,
		arg.TeeColorID,
		arg.Number,
		arg.TenantID,
		arg.Par,
		arg.Hdcp,
		arg.Yards,
	)
	var i Hole
	err := row.Scan(
		&i.CourseID,
		&i.TeeColorID,
		&i.Number,
		&i.TenantID,
		&i.Par,
		&i.Hdcp,
		&i.Yards,
	)
	return i, err
}

const deleteHole = `-- name: DeleteHole :exec
DELETE FROM holes
WHERE course_id = $1 AND tee_color_id = $2 AND number = $3 AND tenant_id = $4
`

type DeleteHoleParams struct {
	CourseID   int32     `json:"course_id"`
	TeeColorID int32     `json:"tee_color_id"`
	Number     int32     `json:"number"`
	TenantID   uuid.UUID `json:"tenant_id"`
}

func (q *Queries) DeleteHole(ctx context.Context, arg DeleteHoleParams) error {
	_, err := q.db.Exec(ctx, deleteHole,
		arg.CourseID,
		arg.TeeColorID,
		arg.Number,
		arg.TenantID,
	)
	return err
}

const getHole = `-- name: GetHole :one
SELECT course_id, tee_color_id, number, tenant_id, par, hdcp, yards FROM holes
WHERE course_id = $1 AND tee_color_id = $2 AND number = $3 AND tenant_id = $4
`

type GetHoleParams struct {
	CourseID   int32     `json:"course_id"`
	TeeColorID int32     `json:"tee_color_id"`
	Number     int32     `json:"number"`
	TenantID   uuid.UUID `json:"tenant_id"`
}

func (q *Queries) GetHole(ctx context.Context, arg GetHoleParams) (Hole, error) {
	row := q.db.QueryRow(ctx, getHole,
		arg.CourseID,
		arg.TeeColorID,
		arg.Number,
		arg.TenantID,
	)
	var i Hole
	err := row.Scan(
		&i.CourseID,
		&i.TeeColorID,
		&i.Number,
		&i.TenantID,
		&i.Par,
		&i.Hdcp,
		&i.Yards,
	)
	return i, err
}

const listHolesByTeeSet = `-- name: ListHolesByTeeSet :many
SELECT course_id, tee_color_id, number, tenant_id, par, hdcp, yards FROM holes
WHERE course_id = $1 AND tee_color_id = $2 AND tenant_id = $3
ORDER BY number
`

type ListHolesByTeeSetParams struct {
	CourseID   int32     `json:"course_id"`
	TeeColorID int32     `json:"tee_color_id"`
	TenantID   uuid.UUID `json:"tenant_id"`
}

func (q *Queries) ListHolesByTeeSet(ctx context.Context, arg ListHolesByTeeSetParams) ([]Hole, error) {
	rows, err := q.db.Query(ctx, listHolesByTeeSet, arg.CourseID, arg.TeeColorID, arg.TenantID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Hole{}
	for rows.Next() {
		var i Hole
		if err := rows.Scan(
			&i.CourseID,
			&i.TeeColorID,
			&i.Number,
			&i.TenantID,
			&i.Par,
			&i.Hdcp,
			&i.Yards,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateHole = `-- name: UpdateHole :one
UPDATE holes
SET
    par = $5,
    hdcp = $6,
    yards = $7
WHERE course_id = $1 AND tee_color_id = $2 AND number = $3 AND tenant_id = $4
RETURNING course_id, tee_color_id, number, tenant_id, par, hdcp, yards
`

type UpdateHoleParams struct {
	CourseID   int32     `json:"course_id"`
	TeeColorID int32     `json:"tee_color_id"`
	Number     int32     `json:"number"`
	TenantID   uuid.UUID `json:"tenant_id"`
	Par        int32     `json:"par"`
	Hdcp       int32     `json:"hdcp"`
	Yards      int32     `json:"yards"`
}

func (q *Queries) UpdateHole(ctx context.Context, arg UpdateHoleParams) (Hole, error) {
	row := q.db.QueryRow(ctx, updateHole,
		arg.CourseID,
		arg.TeeColorID,
		arg.Number,
		arg.TenantID,
		arg.Par,
		arg.Hdcp,
		arg.Yards,
	)
	var i Hole
	err := row.Scan(
		&i.CourseID,
		&i.TeeColorID,
		&i.Number,
		&i.TenantID,
		&i.Par,
		&i.Hdcp,
		&i.Yards,
	)
	return i, err
}
