// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: holes.sql

package sqlc

import (
	"context"

	"github.com/google/uuid"
)

const createHole = `-- name: CreateHole :one
INSERT INTO holes (
    course_id,
    tee_color_id,
    number,
    tenant_id,
    par,
    hdcp,
    yards
) VALUES (
    $1, $2, $3, $4, $5, $6, $7
) RETURNING course_id, tee_color_id, number, tenant_id, par, hdcp, yards
`

type CreateHoleParams struct {
	CourseID   uuid.UUID `json:"course_id"`
	TeeColorID uuid.UUID `json:"tee_color_id"`
	Number     int32     `json:"number"`
	TenantID   uuid.UUID `json:"tenant_id"`
	Par        int32     `json:"par"`
	Hdcp       int32     `json:"hdcp"`
	Yards      int32     `json:"yards"`
}

func (q *Queries) CreateHole(ctx context.Context, arg CreateHoleParams) (Hole, error) {
	row := q.db.QueryRow(ctx, createHole,
		arg.CourseID,
		arg.TeeColorID,
		arg.Number,
		arg.TenantID,
		arg.Par,
		arg.Hdcp,
		arg.Yards,
	)
	var i Hole
	err := row.Scan(
		&i.CourseID,
		&i.TeeColorID,
		&i.Number,
		&i.TenantID,
		&i.Par,
		&i.Hdcp,
		&i.Yards,
	)
	return i, err
}
