// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: match_participants.sql

package sqlc

import (
	"context"

	"github.com/google/uuid"
)

const createMatchParticipant = `-- name: CreateMatchParticipant :one
INSERT INTO match_participants (
    tournament_id,
    match_id,
    player_id,
    team_id,
    tenant_id
) VALUES (
    $1, $2, $3, $4, $5
) RETURNING tournament_id, match_id, player_id, team_id, tenant_id
`

type CreateMatchParticipantParams struct {
	TournamentID uuid.UUID `json:"tournament_id"`
	MatchID      uuid.UUID `json:"match_id"`
	PlayerID     uuid.UUID `json:"player_id"`
	TeamID       uuid.UUID `json:"team_id"`
	TenantID     uuid.UUID `json:"tenant_id"`
}

func (q *Queries) CreateMatchParticipant(ctx context.Context, arg CreateMatchParticipantParams) (MatchParticipant, error) {
	row := q.db.QueryRow(ctx, createMatchParticipant,
		arg.TournamentID,
		arg.MatchID,
		arg.PlayerID,
		arg.TeamID,
		arg.TenantID,
	)
	var i MatchParticipant
	err := row.Scan(
		&i.TournamentID,
		&i.MatchID,
		&i.PlayerID,
		&i.TeamID,
		&i.TenantID,
	)
	return i, err
}

const deleteMatchParticipant = `-- name: DeleteMatchParticipant :exec
DELETE FROM match_participants
WHERE match_id = $1 AND player_id = $2 AND tenant_id = $3
`

type DeleteMatchParticipantParams struct {
	MatchID  uuid.UUID `json:"match_id"`
	PlayerID uuid.UUID `json:"player_id"`
	TenantID uuid.UUID `json:"tenant_id"`
}

func (q *Queries) DeleteMatchParticipant(ctx context.Context, arg DeleteMatchParticipantParams) error {
	_, err := q.db.Exec(ctx, deleteMatchParticipant, arg.MatchID, arg.PlayerID, arg.TenantID)
	return err
}

const getMatchParticipant = `-- name: GetMatchParticipant :one
SELECT tournament_id, match_id, player_id, team_id, tenant_id FROM match_participants
WHERE match_id = $1 AND player_id = $2 AND tenant_id = $3
`

type GetMatchParticipantParams struct {
	MatchID  uuid.UUID `json:"match_id"`
	PlayerID uuid.UUID `json:"player_id"`
	TenantID uuid.UUID `json:"tenant_id"`
}

func (q *Queries) GetMatchParticipant(ctx context.Context, arg GetMatchParticipantParams) (MatchParticipant, error) {
	row := q.db.QueryRow(ctx, getMatchParticipant, arg.MatchID, arg.PlayerID, arg.TenantID)
	var i MatchParticipant
	err := row.Scan(
		&i.TournamentID,
		&i.MatchID,
		&i.PlayerID,
		&i.TeamID,
		&i.TenantID,
	)
	return i, err
}

const listMatchParticipants = `-- name: ListMatchParticipants :many
SELECT tournament_id, match_id, player_id, team_id, tenant_id FROM match_participants
WHERE match_id = $1 AND tenant_id = $2
ORDER BY team_id, player_id
`

type ListMatchParticipantsParams struct {
	MatchID  uuid.UUID `json:"match_id"`
	TenantID uuid.UUID `json:"tenant_id"`
}

func (q *Queries) ListMatchParticipants(ctx context.Context, arg ListMatchParticipantsParams) ([]MatchParticipant, error) {
	rows, err := q.db.Query(ctx, listMatchParticipants, arg.MatchID, arg.TenantID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []MatchParticipant{}
	for rows.Next() {
		var i MatchParticipant
		if err := rows.Scan(
			&i.TournamentID,
			&i.MatchID,
			&i.PlayerID,
			&i.TeamID,
			&i.TenantID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
