// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: match_formats.sql

package sqlc

import (
	"context"

	"github.com/google/uuid"
)

const getMatchFormat = `-- name: GetMatchFormat :one

SELECT id, name FROM match_formats
WHERE id = $1
`

// Match formats are global, code-defined reference data (seeded, not tenant-scoped),
// so these reads take no tenant_id and there is no create/update/delete.
func (q *Queries) GetMatchFormat(ctx context.Context, id uuid.UUID) (MatchFormat, error) {
	row := q.db.QueryRow(ctx, getMatchFormat, id)
	var i MatchFormat
	err := row.Scan(&i.ID, &i.Name)
	return i, err
}

const listMatchFormats = `-- name: ListMatchFormats :many
SELECT id, name FROM match_formats
ORDER BY id
`

func (q *Queries) ListMatchFormats(ctx context.Context) ([]MatchFormat, error) {
	rows, err := q.db.Query(ctx, listMatchFormats)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []MatchFormat{}
	for rows.Next() {
		var i MatchFormat
		if err := rows.Scan(&i.ID, &i.Name); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
