// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: match_participants.sql

package sqlc

import (
	"context"

	"github.com/google/uuid"
)

const createMatchParticipant = `-- name: CreateMatchParticipant :one
INSERT INTO match_participants (
    tournament_id,
    match_id,
    player_id,
    tenant_id
) VALUES (
    $1, $2, $3, $4
) RETURNING tournament_id, match_id, player_id, tenant_id
`

type CreateMatchParticipantParams struct {
	TournamentID int32     `json:"tournament_id"`
	MatchID      int32     `json:"match_id"`
	PlayerID     int32     `json:"player_id"`
	TenantID     uuid.UUID `json:"tenant_id"`
}

func (q *Queries) CreateMatchParticipant(ctx context.Context, arg CreateMatchParticipantParams) (MatchParticipant, error) {
	row := q.db.QueryRow(ctx, createMatchParticipant,
		arg.TournamentID,
		arg.MatchID,
		arg.PlayerID,
		arg.TenantID,
	)
	var i MatchParticipant
	err := row.Scan(
		&i.TournamentID,
		&i.MatchID,
		&i.PlayerID,
		&i.TenantID,
	)
	return i, err
}

const deleteMatchParticipant = `-- name: DeleteMatchParticipant :exec
DELETE FROM match_participants
WHERE match_id = $1 AND player_id = $2 AND tenant_id = $3
`

type DeleteMatchParticipantParams struct {
	MatchID  int32     `json:"match_id"`
	PlayerID int32     `json:"player_id"`
	TenantID uuid.UUID `json:"tenant_id"`
}

func (q *Queries) DeleteMatchParticipant(ctx context.Context, arg DeleteMatchParticipantParams) error {
	_, err := q.db.Exec(ctx, deleteMatchParticipant, arg.MatchID, arg.PlayerID, arg.TenantID)
	return err
}

const getMatchParticipant = `-- name: GetMatchParticipant :one
SELECT tournament_id, match_id, player_id, tenant_id FROM match_participants
WHERE match_id = $1 AND player_id = $2 AND tenant_id = $3
`

type GetMatchParticipantParams struct {
	MatchID  int32     `json:"match_id"`
	PlayerID int32     `json:"player_id"`
	TenantID uuid.UUID `json:"tenant_id"`
}

func (q *Queries) GetMatchParticipant(ctx context.Context, arg GetMatchParticipantParams) (MatchParticipant, error) {
	row := q.db.QueryRow(ctx, getMatchParticipant, arg.MatchID, arg.PlayerID, arg.TenantID)
	var i MatchParticipant
	err := row.Scan(
		&i.TournamentID,
		&i.MatchID,
		&i.PlayerID,
		&i.TenantID,
	)
	return i, err
}

const listMatchParticipants = `-- name: ListMatchParticipants :many
SELECT
    mp.tournament_id, mp.match_id, mp.player_id, mp.tenant_id,
    p.first_name,
    p.last_name,
    p.email,
    p.hdcp,
    p.tier
FROM match_participants mp
JOIN players p ON mp.player_id = p.id
WHERE mp.match_id = $1 AND mp.tenant_id = $2
ORDER BY p.last_name, p.first_name
`

type ListMatchParticipantsParams struct {
	MatchID  int32     `json:"match_id"`
	TenantID uuid.UUID `json:"tenant_id"`
}

type ListMatchParticipantsRow struct {
	TournamentID int32     `json:"tournament_id"`
	MatchID      int32     `json:"match_id"`
	PlayerID     int32     `json:"player_id"`
	TenantID     uuid.UUID `json:"tenant_id"`
	FirstName    string    `json:"first_name"`
	LastName     string    `json:"last_name"`
	Email        string    `json:"email"`
	Hdcp         float32   `json:"hdcp"`
	Tier         string    `json:"tier"`
}

func (q *Queries) ListMatchParticipants(ctx context.Context, arg ListMatchParticipantsParams) ([]ListMatchParticipantsRow, error) {
	rows, err := q.db.Query(ctx, listMatchParticipants, arg.MatchID, arg.TenantID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListMatchParticipantsRow{}
	for rows.Next() {
		var i ListMatchParticipantsRow
		if err := rows.Scan(
			&i.TournamentID,
			&i.MatchID,
			&i.PlayerID,
			&i.TenantID,
			&i.FirstName,
			&i.LastName,
			&i.Email,
			&i.Hdcp,
			&i.Tier,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listMatchParticipantsWithTeam = `-- name: ListMatchParticipantsWithTeam :many
SELECT
    mp.tournament_id, mp.match_id, mp.player_id, mp.tenant_id,
    p.first_name,
    p.last_name,
    p.email,
    p.hdcp,
    p.tier,
    t.name as team_name
FROM match_participants mp
JOIN players p ON mp.player_id = p.id
JOIN team_members tm ON mp.tournament_id = tm.tournament_id AND mp.player_id = tm.player_id
JOIN teams t ON tm.team_id = t.id
WHERE mp.match_id = $1 AND mp.tenant_id = $2
ORDER BY t.name, p.last_name, p.first_name
`

type ListMatchParticipantsWithTeamParams struct {
	MatchID  int32     `json:"match_id"`
	TenantID uuid.UUID `json:"tenant_id"`
}

type ListMatchParticipantsWithTeamRow struct {
	TournamentID int32     `json:"tournament_id"`
	MatchID      int32     `json:"match_id"`
	PlayerID     int32     `json:"player_id"`
	TenantID     uuid.UUID `json:"tenant_id"`
	FirstName    string    `json:"first_name"`
	LastName     string    `json:"last_name"`
	Email        string    `json:"email"`
	Hdcp         float32   `json:"hdcp"`
	Tier         string    `json:"tier"`
	TeamName     string    `json:"team_name"`
}

func (q *Queries) ListMatchParticipantsWithTeam(ctx context.Context, arg ListMatchParticipantsWithTeamParams) ([]ListMatchParticipantsWithTeamRow, error) {
	rows, err := q.db.Query(ctx, listMatchParticipantsWithTeam, arg.MatchID, arg.TenantID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListMatchParticipantsWithTeamRow{}
	for rows.Next() {
		var i ListMatchParticipantsWithTeamRow
		if err := rows.Scan(
			&i.TournamentID,
			&i.MatchID,
			&i.PlayerID,
			&i.TenantID,
			&i.FirstName,
			&i.LastName,
			&i.Email,
			&i.Hdcp,
			&i.Tier,
			&i.TeamName,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
