// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: match_participants.sql

package sqlc

import (
	"context"

	"github.com/google/uuid"
)

const createMatchParticipant = `-- name: CreateMatchParticipant :one
INSERT INTO match_participants (
    tournament_id,
    match_id,
    player_id,
    team_id,
    tenant_id
) VALUES (
    $1, $2, $3, $4, $5
) RETURNING tournament_id, match_id, player_id, team_id, tenant_id
`

type CreateMatchParticipantParams struct {
	TournamentID uuid.UUID `json:"tournament_id"`
	MatchID      uuid.UUID `json:"match_id"`
	PlayerID     uuid.UUID `json:"player_id"`
	TeamID       uuid.UUID `json:"team_id"`
	TenantID     uuid.UUID `json:"tenant_id"`
}

func (q *Queries) CreateMatchParticipant(ctx context.Context, arg CreateMatchParticipantParams) (MatchParticipant, error) {
	row := q.db.QueryRow(ctx, createMatchParticipant,
		arg.TournamentID,
		arg.MatchID,
		arg.PlayerID,
		arg.TeamID,
		arg.TenantID,
	)
	var i MatchParticipant
	err := row.Scan(
		&i.TournamentID,
		&i.MatchID,
		&i.PlayerID,
		&i.TeamID,
		&i.TenantID,
	)
	return i, err
}

const listMatchParticipants = `-- name: ListMatchParticipants :many
SELECT tournament_id, match_id, player_id, team_id, tenant_id FROM match_participants
WHERE match_id = $1 AND tenant_id = $2
ORDER BY team_id, player_id
`

type ListMatchParticipantsParams struct {
	MatchID  uuid.UUID `json:"match_id"`
	TenantID uuid.UUID `json:"tenant_id"`
}

func (q *Queries) ListMatchParticipants(ctx context.Context, arg ListMatchParticipantsParams) ([]MatchParticipant, error) {
	rows, err := q.db.Query(ctx, listMatchParticipants, arg.MatchID, arg.TenantID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []MatchParticipant{}
	for rows.Next() {
		var i MatchParticipant
		if err := rows.Scan(
			&i.TournamentID,
			&i.MatchID,
			&i.PlayerID,
			&i.TeamID,
			&i.TenantID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listParticipantsWithPlayersByTournament = `-- name: ListParticipantsWithPlayersByTournament :many
SELECT mp.match_id, mp.team_id, mp.player_id, p.first_name, p.last_name
FROM match_participants mp
JOIN players p ON p.id = mp.player_id AND p.tenant_id = mp.tenant_id
WHERE mp.tournament_id = $1 AND mp.tenant_id = $2
ORDER BY mp.match_id, mp.team_id, p.last_name, p.first_name
`

type ListParticipantsWithPlayersByTournamentParams struct {
	TournamentID uuid.UUID `json:"tournament_id"`
	TenantID     uuid.UUID `json:"tenant_id"`
}

type ListParticipantsWithPlayersByTournamentRow struct {
	MatchID   uuid.UUID `json:"match_id"`
	TeamID    uuid.UUID `json:"team_id"`
	PlayerID  uuid.UUID `json:"player_id"`
	FirstName string    `json:"first_name"`
	LastName  string    `json:"last_name"`
}

// Every participant across the tournament, with player names, so the results view
// builds each match's sides without a per-match lookup.
func (q *Queries) ListParticipantsWithPlayersByTournament(ctx context.Context, arg ListParticipantsWithPlayersByTournamentParams) ([]ListParticipantsWithPlayersByTournamentRow, error) {
	rows, err := q.db.Query(ctx, listParticipantsWithPlayersByTournament, arg.TournamentID, arg.TenantID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListParticipantsWithPlayersByTournamentRow{}
	for rows.Next() {
		var i ListParticipantsWithPlayersByTournamentRow
		if err := rows.Scan(
			&i.MatchID,
			&i.TeamID,
			&i.PlayerID,
			&i.FirstName,
			&i.LastName,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
