// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: matches.sql

package sqlc

import (
	"context"
	"time"

	"github.com/google/uuid"
)

const createMatch = `-- name: CreateMatch :one
INSERT INTO matches (
    tournament_id,
    course_id,
    tee_color_id,
    match_format_id,
    tenant_id,
    tee_time,
    handicapped
) VALUES (
    $1, $2, $3, $4, $5, $6, $7
) RETURNING id, tournament_id, course_id, tee_color_id, match_format_id, tenant_id, tee_time, handicapped, created_at, updated_at
`

type CreateMatchParams struct {
	TournamentID  uuid.UUID `json:"tournament_id"`
	CourseID      uuid.UUID `json:"course_id"`
	TeeColorID    uuid.UUID `json:"tee_color_id"`
	MatchFormatID uuid.UUID `json:"match_format_id"`
	TenantID      uuid.UUID `json:"tenant_id"`
	TeeTime       time.Time `json:"tee_time"`
	Handicapped   bool      `json:"handicapped"`
}

func (q *Queries) CreateMatch(ctx context.Context, arg CreateMatchParams) (Match, error) {
	row := q.db.QueryRow(ctx, createMatch,
		arg.TournamentID,
		arg.CourseID,
		arg.TeeColorID,
		arg.MatchFormatID,
		arg.TenantID,
		arg.TeeTime,
		arg.Handicapped,
	)
	var i Match
	err := row.Scan(
		&i.ID,
		&i.TournamentID,
		&i.CourseID,
		&i.TeeColorID,
		&i.MatchFormatID,
		&i.TenantID,
		&i.TeeTime,
		&i.Handicapped,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteMatch = `-- name: DeleteMatch :execrows
DELETE FROM matches WHERE id = $1 AND tenant_id = $2
`

type DeleteMatchParams struct {
	ID       uuid.UUID `json:"id"`
	TenantID uuid.UUID `json:"tenant_id"`
}

func (q *Queries) DeleteMatch(ctx context.Context, arg DeleteMatchParams) (int64, error) {
	result, err := q.db.Exec(ctx, deleteMatch, arg.ID, arg.TenantID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const getMatch = `-- name: GetMatch :one
SELECT id, tournament_id, course_id, tee_color_id, match_format_id, tenant_id, tee_time, handicapped, created_at, updated_at FROM matches
WHERE id = $1 AND tenant_id = $2
`

type GetMatchParams struct {
	ID       uuid.UUID `json:"id"`
	TenantID uuid.UUID `json:"tenant_id"`
}

func (q *Queries) GetMatch(ctx context.Context, arg GetMatchParams) (Match, error) {
	row := q.db.QueryRow(ctx, getMatch, arg.ID, arg.TenantID)
	var i Match
	err := row.Scan(
		&i.ID,
		&i.TournamentID,
		&i.CourseID,
		&i.TeeColorID,
		&i.MatchFormatID,
		&i.TenantID,
		&i.TeeTime,
		&i.Handicapped,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listMatchesByTournament = `-- name: ListMatchesByTournament :many
SELECT m.id, m.tournament_id, m.course_id, m.tee_color_id, m.match_format_id, m.tenant_id, m.tee_time, m.handicapped, m.created_at, m.updated_at FROM matches m
WHERE m.tournament_id = $1 AND m.tenant_id = $2
ORDER BY m.tee_time
`

type ListMatchesByTournamentParams struct {
	TournamentID uuid.UUID `json:"tournament_id"`
	TenantID     uuid.UUID `json:"tenant_id"`
}

func (q *Queries) ListMatchesByTournament(ctx context.Context, arg ListMatchesByTournamentParams) ([]Match, error) {
	rows, err := q.db.Query(ctx, listMatchesByTournament, arg.TournamentID, arg.TenantID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Match{}
	for rows.Next() {
		var i Match
		if err := rows.Scan(
			&i.ID,
			&i.TournamentID,
			&i.CourseID,
			&i.TeeColorID,
			&i.MatchFormatID,
			&i.TenantID,
			&i.TeeTime,
			&i.Handicapped,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listMatchesWithDetailsByTournament = `-- name: ListMatchesWithDetailsByTournament :many
SELECT m.id, m.tournament_id, m.course_id, m.tee_color_id, m.match_format_id, m.tenant_id, m.tee_time, m.handicapped, m.created_at, m.updated_at, mf.name AS format_name, mf.scores_per_player, c.name AS course_name
FROM matches m
JOIN match_formats mf ON mf.id = m.match_format_id
JOIN courses c ON c.id = m.course_id AND c.tenant_id = m.tenant_id
WHERE m.tournament_id = $1 AND m.tenant_id = $2
ORDER BY m.tee_time NULLS LAST, m.id
`

type ListMatchesWithDetailsByTournamentParams struct {
	TournamentID uuid.UUID `json:"tournament_id"`
	TenantID     uuid.UUID `json:"tenant_id"`
}

type ListMatchesWithDetailsByTournamentRow struct {
	ID              uuid.UUID `json:"id"`
	TournamentID    uuid.UUID `json:"tournament_id"`
	CourseID        uuid.UUID `json:"course_id"`
	TeeColorID      uuid.UUID `json:"tee_color_id"`
	MatchFormatID   uuid.UUID `json:"match_format_id"`
	TenantID        uuid.UUID `json:"tenant_id"`
	TeeTime         time.Time `json:"tee_time"`
	Handicapped     bool      `json:"handicapped"`
	CreatedAt       time.Time `json:"created_at"`
	UpdatedAt       time.Time `json:"updated_at"`
	FormatName      string    `json:"format_name"`
	ScoresPerPlayer bool      `json:"scores_per_player"`
	CourseName      string    `json:"course_name"`
}

// Joined with the format and course so the results view resolves all of it in one query. The
// format's scoring grain rides along: a client reading a hole needs it, and deriving it from
// the name would be this table's data copied into a list somewhere else.
func (q *Queries) ListMatchesWithDetailsByTournament(ctx context.Context, arg ListMatchesWithDetailsByTournamentParams) ([]ListMatchesWithDetailsByTournamentRow, error) {
	rows, err := q.db.Query(ctx, listMatchesWithDetailsByTournament, arg.TournamentID, arg.TenantID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListMatchesWithDetailsByTournamentRow{}
	for rows.Next() {
		var i ListMatchesWithDetailsByTournamentRow
		if err := rows.Scan(
			&i.ID,
			&i.TournamentID,
			&i.CourseID,
			&i.TeeColorID,
			&i.MatchFormatID,
			&i.TenantID,
			&i.TeeTime,
			&i.Handicapped,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.FormatName,
			&i.ScoresPerPlayer,
			&i.CourseName,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const lockMatch = `-- name: LockMatch :one
SELECT id, tournament_id, course_id, tee_color_id, match_format_id, tenant_id, tee_time, handicapped, created_at, updated_at FROM matches
WHERE id = $1 AND tenant_id = $2
FOR UPDATE
`

type LockMatchParams struct {
	ID       uuid.UUID `json:"id"`
	TenantID uuid.UUID `json:"tenant_id"`
}

// Serializes writes to a match. Each of them reads to decide — whether the match has been
// scored, how many players a side already holds — and then writes on that answer, so without
// this lock two can decide against the same snapshot and the later one acts on an answer that
// stopped being true before it landed.
// Returns the row, not just its id: a caller that locks a match to decide something about it
// needs the match, and reading it again inside the lock cannot say anything different.
func (q *Queries) LockMatch(ctx context.Context, arg LockMatchParams) (Match, error) {
	row := q.db.QueryRow(ctx, lockMatch, arg.ID, arg.TenantID)
	var i Match
	err := row.Scan(
		&i.ID,
		&i.TournamentID,
		&i.CourseID,
		&i.TeeColorID,
		&i.MatchFormatID,
		&i.TenantID,
		&i.TeeTime,
		&i.Handicapped,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updateMatch = `-- name: UpdateMatch :one
UPDATE matches
SET course_id       = COALESCE($1, course_id),
    tee_color_id    = COALESCE($2, tee_color_id),
    tee_time        = COALESCE($3, tee_time),
    handicapped     = COALESCE($4, handicapped)
WHERE id = $5 AND tenant_id = $6
RETURNING id, tournament_id, course_id, tee_color_id, match_format_id, tenant_id, tee_time, handicapped, created_at, updated_at
`

type UpdateMatchParams struct {
	CourseID    *uuid.UUID `json:"course_id"`
	TeeColorID  *uuid.UUID `json:"tee_color_id"`
	TeeTime     *time.Time `json:"tee_time"`
	Handicapped *bool      `json:"handicapped"`
	ID          uuid.UUID  `json:"id"`
	TenantID    uuid.UUID  `json:"tenant_id"`
}

// A null argument leaves the column alone, so a caller changing one field never has to
// read the match first just to echo the rest back. match_format_id is absent rather than
// optional: a match is created in a format and deleted to leave it.
func (q *Queries) UpdateMatch(ctx context.Context, arg UpdateMatchParams) (Match, error) {
	row := q.db.QueryRow(ctx, updateMatch,
		arg.CourseID,
		arg.TeeColorID,
		arg.TeeTime,
		arg.Handicapped,
		arg.ID,
		arg.TenantID,
	)
	var i Match
	err := row.Scan(
		&i.ID,
		&i.TournamentID,
		&i.CourseID,
		&i.TeeColorID,
		&i.MatchFormatID,
		&i.TenantID,
		&i.TeeTime,
		&i.Handicapped,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
