// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: matches.sql

package sqlc

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const createMatch = `-- name: CreateMatch :one
INSERT INTO matches (
    tournament_id,
    course_id,
    tee_color_id,
    match_format_id,
    tenant_id,
    tee_time,
    handicapped
) VALUES (
    $1, $2, $3, $4, $5, $6, $7
) RETURNING id, tournament_id, course_id, tee_color_id, match_format_id, tenant_id, tee_time, handicapped
`

type CreateMatchParams struct {
	TournamentID  int32            `json:"tournament_id"`
	CourseID      int32            `json:"course_id"`
	TeeColorID    int32            `json:"tee_color_id"`
	MatchFormatID int32            `json:"match_format_id"`
	TenantID      uuid.UUID        `json:"tenant_id"`
	TeeTime       pgtype.Timestamp `json:"tee_time"`
	Handicapped   bool             `json:"handicapped"`
}

func (q *Queries) CreateMatch(ctx context.Context, arg CreateMatchParams) (Match, error) {
	row := q.db.QueryRow(ctx, createMatch,
		arg.TournamentID,
		arg.CourseID,
		arg.TeeColorID,
		arg.MatchFormatID,
		arg.TenantID,
		arg.TeeTime,
		arg.Handicapped,
	)
	var i Match
	err := row.Scan(
		&i.ID,
		&i.TournamentID,
		&i.CourseID,
		&i.TeeColorID,
		&i.MatchFormatID,
		&i.TenantID,
		&i.TeeTime,
		&i.Handicapped,
	)
	return i, err
}

const deleteMatch = `-- name: DeleteMatch :exec
DELETE FROM matches
WHERE id = $1 AND tenant_id = $2
`

type DeleteMatchParams struct {
	ID       int32     `json:"id"`
	TenantID uuid.UUID `json:"tenant_id"`
}

func (q *Queries) DeleteMatch(ctx context.Context, arg DeleteMatchParams) error {
	_, err := q.db.Exec(ctx, deleteMatch, arg.ID, arg.TenantID)
	return err
}

const getMatch = `-- name: GetMatch :one
SELECT id, tournament_id, course_id, tee_color_id, match_format_id, tenant_id, tee_time, handicapped FROM matches
WHERE id = $1 AND tenant_id = $2
`

type GetMatchParams struct {
	ID       int32     `json:"id"`
	TenantID uuid.UUID `json:"tenant_id"`
}

func (q *Queries) GetMatch(ctx context.Context, arg GetMatchParams) (Match, error) {
	row := q.db.QueryRow(ctx, getMatch, arg.ID, arg.TenantID)
	var i Match
	err := row.Scan(
		&i.ID,
		&i.TournamentID,
		&i.CourseID,
		&i.TeeColorID,
		&i.MatchFormatID,
		&i.TenantID,
		&i.TeeTime,
		&i.Handicapped,
	)
	return i, err
}

const getMatchWithDetails = `-- name: GetMatchWithDetails :one
SELECT
    m.id, m.tournament_id, m.course_id, m.tee_color_id, m.match_format_id, m.tenant_id, m.tee_time, m.handicapped,
    c.name as course_name,
    tc.color as tee_color_name,
    mf.name as match_format_name,
    t.name as tournament_name
FROM matches m
JOIN courses c ON m.course_id = c.id
JOIN tee_colors tc ON m.tee_color_id = tc.id
JOIN match_formats mf ON m.match_format_id = mf.id
JOIN tournaments t ON m.tournament_id = t.id
WHERE m.id = $1 AND m.tenant_id = $2
`

type GetMatchWithDetailsParams struct {
	ID       int32     `json:"id"`
	TenantID uuid.UUID `json:"tenant_id"`
}

type GetMatchWithDetailsRow struct {
	ID              int32            `json:"id"`
	TournamentID    int32            `json:"tournament_id"`
	CourseID        int32            `json:"course_id"`
	TeeColorID      int32            `json:"tee_color_id"`
	MatchFormatID   int32            `json:"match_format_id"`
	TenantID        uuid.UUID        `json:"tenant_id"`
	TeeTime         pgtype.Timestamp `json:"tee_time"`
	Handicapped     bool             `json:"handicapped"`
	CourseName      string           `json:"course_name"`
	TeeColorName    string           `json:"tee_color_name"`
	MatchFormatName string           `json:"match_format_name"`
	TournamentName  string           `json:"tournament_name"`
}

func (q *Queries) GetMatchWithDetails(ctx context.Context, arg GetMatchWithDetailsParams) (GetMatchWithDetailsRow, error) {
	row := q.db.QueryRow(ctx, getMatchWithDetails, arg.ID, arg.TenantID)
	var i GetMatchWithDetailsRow
	err := row.Scan(
		&i.ID,
		&i.TournamentID,
		&i.CourseID,
		&i.TeeColorID,
		&i.MatchFormatID,
		&i.TenantID,
		&i.TeeTime,
		&i.Handicapped,
		&i.CourseName,
		&i.TeeColorName,
		&i.MatchFormatName,
		&i.TournamentName,
	)
	return i, err
}

const listMatchesByTournament = `-- name: ListMatchesByTournament :many
SELECT
    m.id, m.tournament_id, m.course_id, m.tee_color_id, m.match_format_id, m.tenant_id, m.tee_time, m.handicapped,
    c.name as course_name,
    tc.color as tee_color_name
FROM matches m
JOIN courses c ON m.course_id = c.id
JOIN tee_colors tc ON m.tee_color_id = tc.id
WHERE m.tournament_id = $1 AND m.tenant_id = $2
ORDER BY m.tee_time
`

type ListMatchesByTournamentParams struct {
	TournamentID int32     `json:"tournament_id"`
	TenantID     uuid.UUID `json:"tenant_id"`
}

type ListMatchesByTournamentRow struct {
	ID            int32            `json:"id"`
	TournamentID  int32            `json:"tournament_id"`
	CourseID      int32            `json:"course_id"`
	TeeColorID    int32            `json:"tee_color_id"`
	MatchFormatID int32            `json:"match_format_id"`
	TenantID      uuid.UUID        `json:"tenant_id"`
	TeeTime       pgtype.Timestamp `json:"tee_time"`
	Handicapped   bool             `json:"handicapped"`
	CourseName    string           `json:"course_name"`
	TeeColorName  string           `json:"tee_color_name"`
}

func (q *Queries) ListMatchesByTournament(ctx context.Context, arg ListMatchesByTournamentParams) ([]ListMatchesByTournamentRow, error) {
	rows, err := q.db.Query(ctx, listMatchesByTournament, arg.TournamentID, arg.TenantID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListMatchesByTournamentRow{}
	for rows.Next() {
		var i ListMatchesByTournamentRow
		if err := rows.Scan(
			&i.ID,
			&i.TournamentID,
			&i.CourseID,
			&i.TeeColorID,
			&i.MatchFormatID,
			&i.TenantID,
			&i.TeeTime,
			&i.Handicapped,
			&i.CourseName,
			&i.TeeColorName,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateMatch = `-- name: UpdateMatch :one
UPDATE matches
SET
    course_id = $3,
    tee_color_id = $4,
    match_format_id = $5,
    tee_time = $6,
    handicapped = $7
WHERE id = $1 AND tenant_id = $2
RETURNING id, tournament_id, course_id, tee_color_id, match_format_id, tenant_id, tee_time, handicapped
`

type UpdateMatchParams struct {
	ID            int32            `json:"id"`
	TenantID      uuid.UUID        `json:"tenant_id"`
	CourseID      int32            `json:"course_id"`
	TeeColorID    int32            `json:"tee_color_id"`
	MatchFormatID int32            `json:"match_format_id"`
	TeeTime       pgtype.Timestamp `json:"tee_time"`
	Handicapped   bool             `json:"handicapped"`
}

func (q *Queries) UpdateMatch(ctx context.Context, arg UpdateMatchParams) (Match, error) {
	row := q.db.QueryRow(ctx, updateMatch,
		arg.ID,
		arg.TenantID,
		arg.CourseID,
		arg.TeeColorID,
		arg.MatchFormatID,
		arg.TeeTime,
		arg.Handicapped,
	)
	var i Match
	err := row.Scan(
		&i.ID,
		&i.TournamentID,
		&i.CourseID,
		&i.TeeColorID,
		&i.MatchFormatID,
		&i.TenantID,
		&i.TeeTime,
		&i.Handicapped,
	)
	return i, err
}
