// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package sqlc

import (
	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

type Course struct {
	ID       int32     `json:"id"`
	TenantID uuid.UUID `json:"tenant_id"`
	Name     string    `json:"name"`
}

type Hole struct {
	CourseID   int32     `json:"course_id"`
	TeeColorID int32     `json:"tee_color_id"`
	Number     int32     `json:"number"`
	TenantID   uuid.UUID `json:"tenant_id"`
	Par        int32     `json:"par"`
	Hdcp       int32     `json:"hdcp"`
	Yards      int32     `json:"yards"`
}

type Match struct {
	ID            int32              `json:"id"`
	TournamentID  int32              `json:"tournament_id"`
	CourseID      int32              `json:"course_id"`
	TeeColorID    int32              `json:"tee_color_id"`
	MatchFormatID int32              `json:"match_format_id"`
	TenantID      uuid.UUID          `json:"tenant_id"`
	TeeTime       pgtype.Timestamp   `json:"tee_time"`
	Handicapped   bool               `json:"handicapped"`
	CreatedAt     pgtype.Timestamptz `json:"created_at"`
	UpdatedAt     pgtype.Timestamptz `json:"updated_at"`
}

type MatchFormat struct {
	ID       int32     `json:"id"`
	TenantID uuid.UUID `json:"tenant_id"`
	Name     string    `json:"name"`
}

type MatchParticipant struct {
	TournamentID int32     `json:"tournament_id"`
	MatchID      int32     `json:"match_id"`
	PlayerID     int32     `json:"player_id"`
	TeamID       int32     `json:"team_id"`
	TenantID     uuid.UUID `json:"tenant_id"`
}

type MatchResult struct {
	MatchID        int32              `json:"match_id"`
	TournamentID   int32              `json:"tournament_id"`
	TenantID       uuid.UUID          `json:"tenant_id"`
	Finished       bool               `json:"finished"`
	LeaderTeamID   *int32             `json:"leader_team_id"`
	Lead           int32              `json:"lead"`
	HolesRemaining int32              `json:"holes_remaining"`
	UpdatedAt      pgtype.Timestamptz `json:"updated_at"`
}

type Player struct {
	ID        int32              `json:"id"`
	TenantID  uuid.UUID          `json:"tenant_id"`
	UserID    pgtype.UUID        `json:"user_id"`
	Email     *string            `json:"email"`
	FirstName string             `json:"first_name"`
	LastName  string             `json:"last_name"`
	PhotoPath string             `json:"photo_path"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
	UpdatedAt pgtype.Timestamptz `json:"updated_at"`
}

type Score struct {
	ID         int32              `json:"id"`
	MatchID    int32              `json:"match_id"`
	TeamID     int32              `json:"team_id"`
	PlayerID   *int32             `json:"player_id"`
	CourseID   int32              `json:"course_id"`
	TeeColorID int32              `json:"tee_color_id"`
	HoleNumber int32              `json:"hole_number"`
	TenantID   uuid.UUID          `json:"tenant_id"`
	Strokes    int32              `json:"strokes"`
	CreatedAt  pgtype.Timestamptz `json:"created_at"`
	UpdatedAt  pgtype.Timestamptz `json:"updated_at"`
}

type Team struct {
	ID           int32     `json:"id"`
	TenantID     uuid.UUID `json:"tenant_id"`
	TournamentID int32     `json:"tournament_id"`
	Color        string    `json:"color"`
	CaptainID    *int32    `json:"captain_id"`
}

type TeamMember struct {
	TeamID       int32     `json:"team_id"`
	PlayerID     int32     `json:"player_id"`
	TournamentID int32     `json:"tournament_id"`
	TenantID     uuid.UUID `json:"tenant_id"`
	Tier         string    `json:"tier"`
	Biography    string    `json:"biography"`
	Hdcp         float32   `json:"hdcp"`
}

type TeeColor struct {
	ID       int32     `json:"id"`
	TenantID uuid.UUID `json:"tenant_id"`
	Color    string    `json:"color"`
}

type TeeSet struct {
	CourseID   int32          `json:"course_id"`
	TeeColorID int32          `json:"tee_color_id"`
	TenantID   uuid.UUID      `json:"tenant_id"`
	Slope      int32          `json:"slope"`
	Rating     pgtype.Numeric `json:"rating"`
}

type Tournament struct {
	ID        int32              `json:"id"`
	TenantID  uuid.UUID          `json:"tenant_id"`
	Name      string             `json:"name"`
	StartDate pgtype.Date        `json:"start_date"`
	EndDate   pgtype.Date        `json:"end_date"`
	Location  string             `json:"location"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
	UpdatedAt pgtype.Timestamptz `json:"updated_at"`
}
