// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package sqlc

import (
	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

type Course struct {
	ID       int32     `json:"id"`
	TenantID uuid.UUID `json:"tenant_id"`
	Name     string    `json:"name"`
}

type Hole struct {
	CourseID   int32     `json:"course_id"`
	TeeColorID int32     `json:"tee_color_id"`
	Number     int32     `json:"number"`
	TenantID   uuid.UUID `json:"tenant_id"`
	Par        int32     `json:"par"`
	Hdcp       int32     `json:"hdcp"`
	Yards      int32     `json:"yards"`
}

type Match struct {
	ID            int32            `json:"id"`
	TournamentID  int32            `json:"tournament_id"`
	CourseID      int32            `json:"course_id"`
	TeeColorID    int32            `json:"tee_color_id"`
	MatchFormatID int32            `json:"match_format_id"`
	TenantID      uuid.UUID        `json:"tenant_id"`
	TeeTime       pgtype.Timestamp `json:"tee_time"`
	Handicapped   bool             `json:"handicapped"`
}

type MatchFormat struct {
	ID       int32     `json:"id"`
	TenantID uuid.UUID `json:"tenant_id"`
	Name     string    `json:"name"`
}

type MatchParticipant struct {
	TournamentID int32     `json:"tournament_id"`
	MatchID      int32     `json:"match_id"`
	PlayerID     int32     `json:"player_id"`
	TenantID     uuid.UUID `json:"tenant_id"`
}

type Player struct {
	ID        int32     `json:"id"`
	TenantID  uuid.UUID `json:"tenant_id"`
	Email     string    `json:"email"`
	FirstName string    `json:"first_name"`
	LastName  string    `json:"last_name"`
	Hdcp      float32   `json:"hdcp"`
	PhotoPath *string   `json:"photo_path"`
	Biography *string   `json:"biography"`
	Tier      string    `json:"tier"`
	Cups      int32     `json:"cups"`
	Wins      int32     `json:"wins"`
	Ties      int32     `json:"ties"`
	Losses    int32     `json:"losses"`
}

type Score struct {
	MatchID    int32     `json:"match_id"`
	PlayerID   int32     `json:"player_id"`
	CourseID   int32     `json:"course_id"`
	TeeColorID int32     `json:"tee_color_id"`
	HoleNumber int32     `json:"hole_number"`
	TenantID   uuid.UUID `json:"tenant_id"`
	Strokes    int32     `json:"strokes"`
}

type Team struct {
	ID       int32     `json:"id"`
	TenantID uuid.UUID `json:"tenant_id"`
	Name     string    `json:"name"`
}

type TeamMember struct {
	TournamentID int32     `json:"tournament_id"`
	PlayerID     int32     `json:"player_id"`
	TeamID       int32     `json:"team_id"`
	TenantID     uuid.UUID `json:"tenant_id"`
	IsCaptain    bool      `json:"is_captain"`
}

type TeeColor struct {
	ID       int32     `json:"id"`
	TenantID uuid.UUID `json:"tenant_id"`
	Color    string    `json:"color"`
}

type TeeSet struct {
	CourseID   int32          `json:"course_id"`
	TeeColorID int32          `json:"tee_color_id"`
	TenantID   uuid.UUID      `json:"tenant_id"`
	Slope      int32          `json:"slope"`
	Rating     pgtype.Numeric `json:"rating"`
}

type Tournament struct {
	ID        int32       `json:"id"`
	TenantID  uuid.UUID   `json:"tenant_id"`
	Name      string      `json:"name"`
	StartDate pgtype.Date `json:"start_date"`
	EndDate   pgtype.Date `json:"end_date"`
	Location  string      `json:"location"`
}
