// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package sqlc

import (
	"time"

	"github.com/google/uuid"
)

type Course struct {
	ID       uuid.UUID `json:"id"`
	TenantID uuid.UUID `json:"tenant_id"`
	Name     string    `json:"name"`
}

type FinishedTournament struct {
	TenantID     uuid.UUID `json:"tenant_id"`
	TournamentID uuid.UUID `json:"tournament_id"`
}

type Hole struct {
	CourseID   uuid.UUID `json:"course_id"`
	TeeColorID uuid.UUID `json:"tee_color_id"`
	Number     int32     `json:"number"`
	TenantID   uuid.UUID `json:"tenant_id"`
	Par        int32     `json:"par"`
	Hdcp       int32     `json:"hdcp"`
	Yards      int32     `json:"yards"`
}

type Match struct {
	ID            uuid.UUID  `json:"id"`
	TournamentID  uuid.UUID  `json:"tournament_id"`
	CourseID      uuid.UUID  `json:"course_id"`
	TeeColorID    uuid.UUID  `json:"tee_color_id"`
	MatchFormatID uuid.UUID  `json:"match_format_id"`
	TenantID      uuid.UUID  `json:"tenant_id"`
	TeeTime       *time.Time `json:"tee_time"`
	Handicapped   bool       `json:"handicapped"`
	CreatedAt     time.Time  `json:"created_at"`
	UpdatedAt     time.Time  `json:"updated_at"`
}

type MatchFormat struct {
	ID   uuid.UUID `json:"id"`
	Name string    `json:"name"`
}

type MatchParticipant struct {
	TournamentID uuid.UUID `json:"tournament_id"`
	MatchID      uuid.UUID `json:"match_id"`
	PlayerID     uuid.UUID `json:"player_id"`
	TeamID       uuid.UUID `json:"team_id"`
	TenantID     uuid.UUID `json:"tenant_id"`
}

type MatchResult struct {
	MatchID        uuid.UUID  `json:"match_id"`
	TournamentID   uuid.UUID  `json:"tournament_id"`
	TenantID       uuid.UUID  `json:"tenant_id"`
	Finished       bool       `json:"finished"`
	LeaderTeamID   *uuid.UUID `json:"leader_team_id"`
	Lead           int32      `json:"lead"`
	HolesRemaining int32      `json:"holes_remaining"`
	UpdatedAt      time.Time  `json:"updated_at"`
}

type Player struct {
	ID        uuid.UUID  `json:"id"`
	TenantID  uuid.UUID  `json:"tenant_id"`
	UserID    *uuid.UUID `json:"user_id"`
	Email     *string    `json:"email"`
	FirstName string     `json:"first_name"`
	LastName  string     `json:"last_name"`
	PhotoPath string     `json:"photo_path"`
	CreatedAt time.Time  `json:"created_at"`
	UpdatedAt time.Time  `json:"updated_at"`
}

type PlayerMatchOutcome struct {
	TenantID     uuid.UUID `json:"tenant_id"`
	TournamentID uuid.UUID `json:"tournament_id"`
	PlayerID     uuid.UUID `json:"player_id"`
	MatchID      uuid.UUID `json:"match_id"`
	Won          *bool     `json:"won"`
	Lost         *bool     `json:"lost"`
	Tied         *bool     `json:"tied"`
}

type Score struct {
	ID         uuid.UUID  `json:"id"`
	MatchID    uuid.UUID  `json:"match_id"`
	TeamID     uuid.UUID  `json:"team_id"`
	PlayerID   *uuid.UUID `json:"player_id"`
	CourseID   uuid.UUID  `json:"course_id"`
	TeeColorID uuid.UUID  `json:"tee_color_id"`
	HoleNumber int32      `json:"hole_number"`
	TenantID   uuid.UUID  `json:"tenant_id"`
	Strokes    int32      `json:"strokes"`
	CreatedAt  time.Time  `json:"created_at"`
	UpdatedAt  time.Time  `json:"updated_at"`
}

type Team struct {
	ID           uuid.UUID  `json:"id"`
	TenantID     uuid.UUID  `json:"tenant_id"`
	TournamentID uuid.UUID  `json:"tournament_id"`
	Color        string     `json:"color"`
	CaptainID    *uuid.UUID `json:"captain_id"`
}

type TeamMember struct {
	TeamID       uuid.UUID `json:"team_id"`
	PlayerID     uuid.UUID `json:"player_id"`
	TournamentID uuid.UUID `json:"tournament_id"`
	TenantID     uuid.UUID `json:"tenant_id"`
}

type TeamPoint struct {
	TenantID     uuid.UUID `json:"tenant_id"`
	TournamentID uuid.UUID `json:"tournament_id"`
	TeamID       uuid.UUID `json:"team_id"`
	Points       float64   `json:"points"`
}

type TeeColor struct {
	ID       uuid.UUID `json:"id"`
	TenantID uuid.UUID `json:"tenant_id"`
	Color    string    `json:"color"`
}

type TeeSet struct {
	CourseID   uuid.UUID `json:"course_id"`
	TeeColorID uuid.UUID `json:"tee_color_id"`
	TenantID   uuid.UUID `json:"tenant_id"`
	Slope      int32     `json:"slope"`
	Rating     float64   `json:"rating"`
}

type Tournament struct {
	ID        uuid.UUID `json:"id"`
	TenantID  uuid.UUID `json:"tenant_id"`
	Name      string    `json:"name"`
	StartDate time.Time `json:"start_date"`
	EndDate   time.Time `json:"end_date"`
	Location  string    `json:"location"`
	CreatedAt time.Time `json:"created_at"`
	UpdatedAt time.Time `json:"updated_at"`
}

type TournamentPlayer struct {
	TournamentID uuid.UUID `json:"tournament_id"`
	PlayerID     uuid.UUID `json:"player_id"`
	TenantID     uuid.UUID `json:"tenant_id"`
	Tier         string    `json:"tier"`
	Biography    string    `json:"biography"`
	Hdcp         float32   `json:"hdcp"`
	CreatedAt    time.Time `json:"created_at"`
	UpdatedAt    time.Time `json:"updated_at"`
}

type TournamentWinner struct {
	TenantID     uuid.UUID `json:"tenant_id"`
	TournamentID uuid.UUID `json:"tournament_id"`
	TeamID       uuid.UUID `json:"team_id"`
}
