// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: players.sql

package sqlc

import (
	"context"

	"github.com/google/uuid"
)

const createPlayer = `-- name: CreatePlayer :one
INSERT INTO players (
    tenant_id,
    user_id,
    email,
    first_name,
    last_name,
    photo_path
) VALUES (
    $1, $2, $3, $4, $5, $6
) RETURNING id, tenant_id, user_id, email, first_name, last_name, photo_path, created_at, updated_at
`

type CreatePlayerParams struct {
	TenantID  uuid.UUID  `json:"tenant_id"`
	UserID    *uuid.UUID `json:"user_id"`
	Email     *string    `json:"email"`
	FirstName string     `json:"first_name"`
	LastName  string     `json:"last_name"`
	PhotoPath string     `json:"photo_path"`
}

func (q *Queries) CreatePlayer(ctx context.Context, arg CreatePlayerParams) (Player, error) {
	row := q.db.QueryRow(ctx, createPlayer,
		arg.TenantID,
		arg.UserID,
		arg.Email,
		arg.FirstName,
		arg.LastName,
		arg.PhotoPath,
	)
	var i Player
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.UserID,
		&i.Email,
		&i.FirstName,
		&i.LastName,
		&i.PhotoPath,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getPlayer = `-- name: GetPlayer :one
SELECT id, tenant_id, user_id, email, first_name, last_name, photo_path, created_at, updated_at FROM players
WHERE id = $1 AND tenant_id = $2
`

type GetPlayerParams struct {
	ID       uuid.UUID `json:"id"`
	TenantID uuid.UUID `json:"tenant_id"`
}

func (q *Queries) GetPlayer(ctx context.Context, arg GetPlayerParams) (Player, error) {
	row := q.db.QueryRow(ctx, getPlayer, arg.ID, arg.TenantID)
	var i Player
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.UserID,
		&i.Email,
		&i.FirstName,
		&i.LastName,
		&i.PhotoPath,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listPlayers = `-- name: ListPlayers :many
SELECT id, tenant_id, user_id, email, first_name, last_name, photo_path, created_at, updated_at FROM players
WHERE tenant_id = $1
ORDER BY last_name, first_name
`

func (q *Queries) ListPlayers(ctx context.Context, tenantID uuid.UUID) ([]Player, error) {
	rows, err := q.db.Query(ctx, listPlayers, tenantID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Player{}
	for rows.Next() {
		var i Player
		if err := rows.Scan(
			&i.ID,
			&i.TenantID,
			&i.UserID,
			&i.Email,
			&i.FirstName,
			&i.LastName,
			&i.PhotoPath,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
