// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: players.sql

package sqlc

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const createPlayer = `-- name: CreatePlayer :one
INSERT INTO players (
    tenant_id,
    user_id,
    email,
    first_name,
    last_name,
    photo_path
) VALUES (
    $1, $2, $3, $4, $5, $6
) RETURNING id, tenant_id, user_id, email, first_name, last_name, photo_path, cups, wins, ties, losses, created_at, updated_at
`

type CreatePlayerParams struct {
	TenantID  uuid.UUID   `json:"tenant_id"`
	UserID    pgtype.UUID `json:"user_id"`
	Email     *string     `json:"email"`
	FirstName string      `json:"first_name"`
	LastName  string      `json:"last_name"`
	PhotoPath string      `json:"photo_path"`
}

func (q *Queries) CreatePlayer(ctx context.Context, arg CreatePlayerParams) (Player, error) {
	row := q.db.QueryRow(ctx, createPlayer,
		arg.TenantID,
		arg.UserID,
		arg.Email,
		arg.FirstName,
		arg.LastName,
		arg.PhotoPath,
	)
	var i Player
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.UserID,
		&i.Email,
		&i.FirstName,
		&i.LastName,
		&i.PhotoPath,
		&i.Cups,
		&i.Wins,
		&i.Ties,
		&i.Losses,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deletePlayer = `-- name: DeletePlayer :exec
DELETE FROM players
WHERE id = $1 AND tenant_id = $2
`

type DeletePlayerParams struct {
	ID       int32     `json:"id"`
	TenantID uuid.UUID `json:"tenant_id"`
}

func (q *Queries) DeletePlayer(ctx context.Context, arg DeletePlayerParams) error {
	_, err := q.db.Exec(ctx, deletePlayer, arg.ID, arg.TenantID)
	return err
}

const getPlayer = `-- name: GetPlayer :one
SELECT id, tenant_id, user_id, email, first_name, last_name, photo_path, cups, wins, ties, losses, created_at, updated_at FROM players
WHERE id = $1 AND tenant_id = $2
`

type GetPlayerParams struct {
	ID       int32     `json:"id"`
	TenantID uuid.UUID `json:"tenant_id"`
}

func (q *Queries) GetPlayer(ctx context.Context, arg GetPlayerParams) (Player, error) {
	row := q.db.QueryRow(ctx, getPlayer, arg.ID, arg.TenantID)
	var i Player
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.UserID,
		&i.Email,
		&i.FirstName,
		&i.LastName,
		&i.PhotoPath,
		&i.Cups,
		&i.Wins,
		&i.Ties,
		&i.Losses,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getPlayerByEmail = `-- name: GetPlayerByEmail :one
SELECT id, tenant_id, user_id, email, first_name, last_name, photo_path, cups, wins, ties, losses, created_at, updated_at FROM players
WHERE email = $1 AND tenant_id = $2
`

type GetPlayerByEmailParams struct {
	Email    *string   `json:"email"`
	TenantID uuid.UUID `json:"tenant_id"`
}

func (q *Queries) GetPlayerByEmail(ctx context.Context, arg GetPlayerByEmailParams) (Player, error) {
	row := q.db.QueryRow(ctx, getPlayerByEmail, arg.Email, arg.TenantID)
	var i Player
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.UserID,
		&i.Email,
		&i.FirstName,
		&i.LastName,
		&i.PhotoPath,
		&i.Cups,
		&i.Wins,
		&i.Ties,
		&i.Losses,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listPlayers = `-- name: ListPlayers :many
SELECT id, tenant_id, user_id, email, first_name, last_name, photo_path, cups, wins, ties, losses, created_at, updated_at FROM players
WHERE tenant_id = $1
ORDER BY last_name, first_name
`

func (q *Queries) ListPlayers(ctx context.Context, tenantID uuid.UUID) ([]Player, error) {
	rows, err := q.db.Query(ctx, listPlayers, tenantID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Player{}
	for rows.Next() {
		var i Player
		if err := rows.Scan(
			&i.ID,
			&i.TenantID,
			&i.UserID,
			&i.Email,
			&i.FirstName,
			&i.LastName,
			&i.PhotoPath,
			&i.Cups,
			&i.Wins,
			&i.Ties,
			&i.Losses,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updatePlayer = `-- name: UpdatePlayer :one
UPDATE players
SET
    user_id = $3,
    email = $4,
    first_name = $5,
    last_name = $6,
    photo_path = $7,
    updated_at = now()
WHERE id = $1 AND tenant_id = $2
RETURNING id, tenant_id, user_id, email, first_name, last_name, photo_path, cups, wins, ties, losses, created_at, updated_at
`

type UpdatePlayerParams struct {
	ID        int32       `json:"id"`
	TenantID  uuid.UUID   `json:"tenant_id"`
	UserID    pgtype.UUID `json:"user_id"`
	Email     *string     `json:"email"`
	FirstName string      `json:"first_name"`
	LastName  string      `json:"last_name"`
	PhotoPath string      `json:"photo_path"`
}

func (q *Queries) UpdatePlayer(ctx context.Context, arg UpdatePlayerParams) (Player, error) {
	row := q.db.QueryRow(ctx, updatePlayer,
		arg.ID,
		arg.TenantID,
		arg.UserID,
		arg.Email,
		arg.FirstName,
		arg.LastName,
		arg.PhotoPath,
	)
	var i Player
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.UserID,
		&i.Email,
		&i.FirstName,
		&i.LastName,
		&i.PhotoPath,
		&i.Cups,
		&i.Wins,
		&i.Ties,
		&i.Losses,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updatePlayerStats = `-- name: UpdatePlayerStats :one
UPDATE players
SET
    wins = $3,
    losses = $4,
    ties = $5,
    cups = $6,
    updated_at = now()
WHERE id = $1 AND tenant_id = $2
RETURNING id, tenant_id, user_id, email, first_name, last_name, photo_path, cups, wins, ties, losses, created_at, updated_at
`

type UpdatePlayerStatsParams struct {
	ID       int32     `json:"id"`
	TenantID uuid.UUID `json:"tenant_id"`
	Wins     int32     `json:"wins"`
	Losses   int32     `json:"losses"`
	Ties     int32     `json:"ties"`
	Cups     int32     `json:"cups"`
}

func (q *Queries) UpdatePlayerStats(ctx context.Context, arg UpdatePlayerStatsParams) (Player, error) {
	row := q.db.QueryRow(ctx, updatePlayerStats,
		arg.ID,
		arg.TenantID,
		arg.Wins,
		arg.Losses,
		arg.Ties,
		arg.Cups,
	)
	var i Player
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.UserID,
		&i.Email,
		&i.FirstName,
		&i.LastName,
		&i.PhotoPath,
		&i.Cups,
		&i.Wins,
		&i.Ties,
		&i.Losses,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
