// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: scores.sql

package sqlc

import (
	"context"

	"github.com/google/uuid"
)

const createScore = `-- name: CreateScore :one
INSERT INTO scores (
    match_id,
    player_id,
    course_id,
    tee_color_id,
    hole_number,
    tenant_id,
    strokes
) VALUES (
    $1, $2, $3, $4, $5, $6, $7
) RETURNING match_id, player_id, course_id, tee_color_id, hole_number, tenant_id, strokes
`

type CreateScoreParams struct {
	MatchID    int32     `json:"match_id"`
	PlayerID   int32     `json:"player_id"`
	CourseID   int32     `json:"course_id"`
	TeeColorID int32     `json:"tee_color_id"`
	HoleNumber int32     `json:"hole_number"`
	TenantID   uuid.UUID `json:"tenant_id"`
	Strokes    int32     `json:"strokes"`
}

func (q *Queries) CreateScore(ctx context.Context, arg CreateScoreParams) (Score, error) {
	row := q.db.QueryRow(ctx, createScore,
		arg.MatchID,
		arg.PlayerID,
		arg.CourseID,
		arg.TeeColorID,
		arg.HoleNumber,
		arg.TenantID,
		arg.Strokes,
	)
	var i Score
	err := row.Scan(
		&i.MatchID,
		&i.PlayerID,
		&i.CourseID,
		&i.TeeColorID,
		&i.HoleNumber,
		&i.TenantID,
		&i.Strokes,
	)
	return i, err
}

const deleteScore = `-- name: DeleteScore :exec
DELETE FROM scores
WHERE match_id = $1 AND player_id = $2 AND hole_number = $3 AND tenant_id = $4
`

type DeleteScoreParams struct {
	MatchID    int32     `json:"match_id"`
	PlayerID   int32     `json:"player_id"`
	HoleNumber int32     `json:"hole_number"`
	TenantID   uuid.UUID `json:"tenant_id"`
}

func (q *Queries) DeleteScore(ctx context.Context, arg DeleteScoreParams) error {
	_, err := q.db.Exec(ctx, deleteScore,
		arg.MatchID,
		arg.PlayerID,
		arg.HoleNumber,
		arg.TenantID,
	)
	return err
}

const deleteScoresByMatch = `-- name: DeleteScoresByMatch :exec
DELETE FROM scores
WHERE match_id = $1 AND tenant_id = $2
`

type DeleteScoresByMatchParams struct {
	MatchID  int32     `json:"match_id"`
	TenantID uuid.UUID `json:"tenant_id"`
}

func (q *Queries) DeleteScoresByMatch(ctx context.Context, arg DeleteScoresByMatchParams) error {
	_, err := q.db.Exec(ctx, deleteScoresByMatch, arg.MatchID, arg.TenantID)
	return err
}

const getScore = `-- name: GetScore :one
SELECT match_id, player_id, course_id, tee_color_id, hole_number, tenant_id, strokes FROM scores
WHERE match_id = $1 AND player_id = $2 AND hole_number = $3 AND tenant_id = $4
`

type GetScoreParams struct {
	MatchID    int32     `json:"match_id"`
	PlayerID   int32     `json:"player_id"`
	HoleNumber int32     `json:"hole_number"`
	TenantID   uuid.UUID `json:"tenant_id"`
}

func (q *Queries) GetScore(ctx context.Context, arg GetScoreParams) (Score, error) {
	row := q.db.QueryRow(ctx, getScore,
		arg.MatchID,
		arg.PlayerID,
		arg.HoleNumber,
		arg.TenantID,
	)
	var i Score
	err := row.Scan(
		&i.MatchID,
		&i.PlayerID,
		&i.CourseID,
		&i.TeeColorID,
		&i.HoleNumber,
		&i.TenantID,
		&i.Strokes,
	)
	return i, err
}

const listScoresByMatch = `-- name: ListScoresByMatch :many
SELECT
    s.match_id, s.player_id, s.course_id, s.tee_color_id, s.hole_number, s.tenant_id, s.strokes,
    h.par,
    h.hdcp as hole_hdcp,
    p.first_name,
    p.last_name,
    p.hdcp as player_hdcp
FROM scores s
JOIN holes h ON s.course_id = h.course_id
    AND s.tee_color_id = h.tee_color_id
    AND s.hole_number = h.number
JOIN players p ON s.player_id = p.id
WHERE s.match_id = $1 AND s.tenant_id = $2
ORDER BY s.hole_number, p.last_name
`

type ListScoresByMatchParams struct {
	MatchID  int32     `json:"match_id"`
	TenantID uuid.UUID `json:"tenant_id"`
}

type ListScoresByMatchRow struct {
	MatchID    int32     `json:"match_id"`
	PlayerID   int32     `json:"player_id"`
	CourseID   int32     `json:"course_id"`
	TeeColorID int32     `json:"tee_color_id"`
	HoleNumber int32     `json:"hole_number"`
	TenantID   uuid.UUID `json:"tenant_id"`
	Strokes    int32     `json:"strokes"`
	Par        int32     `json:"par"`
	HoleHdcp   int32     `json:"hole_hdcp"`
	FirstName  string    `json:"first_name"`
	LastName   string    `json:"last_name"`
	PlayerHdcp float32   `json:"player_hdcp"`
}

func (q *Queries) ListScoresByMatch(ctx context.Context, arg ListScoresByMatchParams) ([]ListScoresByMatchRow, error) {
	rows, err := q.db.Query(ctx, listScoresByMatch, arg.MatchID, arg.TenantID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListScoresByMatchRow{}
	for rows.Next() {
		var i ListScoresByMatchRow
		if err := rows.Scan(
			&i.MatchID,
			&i.PlayerID,
			&i.CourseID,
			&i.TeeColorID,
			&i.HoleNumber,
			&i.TenantID,
			&i.Strokes,
			&i.Par,
			&i.HoleHdcp,
			&i.FirstName,
			&i.LastName,
			&i.PlayerHdcp,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listScoresByMatchAndPlayer = `-- name: ListScoresByMatchAndPlayer :many
SELECT
    s.match_id, s.player_id, s.course_id, s.tee_color_id, s.hole_number, s.tenant_id, s.strokes,
    h.par,
    h.hdcp as hole_hdcp,
    h.yards
FROM scores s
JOIN holes h ON s.course_id = h.course_id
    AND s.tee_color_id = h.tee_color_id
    AND s.hole_number = h.number
WHERE s.match_id = $1 AND s.player_id = $2 AND s.tenant_id = $3
ORDER BY s.hole_number
`

type ListScoresByMatchAndPlayerParams struct {
	MatchID  int32     `json:"match_id"`
	PlayerID int32     `json:"player_id"`
	TenantID uuid.UUID `json:"tenant_id"`
}

type ListScoresByMatchAndPlayerRow struct {
	MatchID    int32     `json:"match_id"`
	PlayerID   int32     `json:"player_id"`
	CourseID   int32     `json:"course_id"`
	TeeColorID int32     `json:"tee_color_id"`
	HoleNumber int32     `json:"hole_number"`
	TenantID   uuid.UUID `json:"tenant_id"`
	Strokes    int32     `json:"strokes"`
	Par        int32     `json:"par"`
	HoleHdcp   int32     `json:"hole_hdcp"`
	Yards      int32     `json:"yards"`
}

func (q *Queries) ListScoresByMatchAndPlayer(ctx context.Context, arg ListScoresByMatchAndPlayerParams) ([]ListScoresByMatchAndPlayerRow, error) {
	rows, err := q.db.Query(ctx, listScoresByMatchAndPlayer, arg.MatchID, arg.PlayerID, arg.TenantID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListScoresByMatchAndPlayerRow{}
	for rows.Next() {
		var i ListScoresByMatchAndPlayerRow
		if err := rows.Scan(
			&i.MatchID,
			&i.PlayerID,
			&i.CourseID,
			&i.TeeColorID,
			&i.HoleNumber,
			&i.TenantID,
			&i.Strokes,
			&i.Par,
			&i.HoleHdcp,
			&i.Yards,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateScore = `-- name: UpdateScore :one
UPDATE scores
SET strokes = $4
WHERE match_id = $1 AND player_id = $2 AND hole_number = $3 AND tenant_id = $5
RETURNING match_id, player_id, course_id, tee_color_id, hole_number, tenant_id, strokes
`

type UpdateScoreParams struct {
	MatchID    int32     `json:"match_id"`
	PlayerID   int32     `json:"player_id"`
	HoleNumber int32     `json:"hole_number"`
	Strokes    int32     `json:"strokes"`
	TenantID   uuid.UUID `json:"tenant_id"`
}

func (q *Queries) UpdateScore(ctx context.Context, arg UpdateScoreParams) (Score, error) {
	row := q.db.QueryRow(ctx, updateScore,
		arg.MatchID,
		arg.PlayerID,
		arg.HoleNumber,
		arg.Strokes,
		arg.TenantID,
	)
	var i Score
	err := row.Scan(
		&i.MatchID,
		&i.PlayerID,
		&i.CourseID,
		&i.TeeColorID,
		&i.HoleNumber,
		&i.TenantID,
		&i.Strokes,
	)
	return i, err
}
