// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: scores.sql

package sqlc

import (
	"context"
	"time"

	"github.com/google/uuid"
)

const deleteScoresByMatch = `-- name: DeleteScoresByMatch :exec
DELETE FROM scores
WHERE match_id = $1 AND tenant_id = $2
`

type DeleteScoresByMatchParams struct {
	MatchID  uuid.UUID `json:"match_id"`
	TenantID uuid.UUID `json:"tenant_id"`
}

func (q *Queries) DeleteScoresByMatch(ctx context.Context, arg DeleteScoresByMatchParams) error {
	_, err := q.db.Exec(ctx, deleteScoresByMatch, arg.MatchID, arg.TenantID)
	return err
}

const listScoresByMatch = `-- name: ListScoresByMatch :many
SELECT
    s.id, s.match_id, s.team_id, s.player_id, s.course_id, s.tee_color_id, s.hole_number, s.tenant_id, s.strokes, s.created_at, s.updated_at,
    h.par,
    h.hdcp AS hole_hdcp,
    h.yards
FROM scores s
JOIN holes h ON s.course_id = h.course_id
    AND s.tee_color_id = h.tee_color_id
    AND s.hole_number = h.number
WHERE s.match_id = $1 AND s.tenant_id = $2
ORDER BY s.hole_number
`

type ListScoresByMatchParams struct {
	MatchID  uuid.UUID `json:"match_id"`
	TenantID uuid.UUID `json:"tenant_id"`
}

type ListScoresByMatchRow struct {
	ID         uuid.UUID  `json:"id"`
	MatchID    uuid.UUID  `json:"match_id"`
	TeamID     uuid.UUID  `json:"team_id"`
	PlayerID   *uuid.UUID `json:"player_id"`
	CourseID   uuid.UUID  `json:"course_id"`
	TeeColorID uuid.UUID  `json:"tee_color_id"`
	HoleNumber int32      `json:"hole_number"`
	TenantID   uuid.UUID  `json:"tenant_id"`
	Strokes    int32      `json:"strokes"`
	CreatedAt  time.Time  `json:"created_at"`
	UpdatedAt  time.Time  `json:"updated_at"`
	Par        int32      `json:"par"`
	HoleHdcp   int32      `json:"hole_hdcp"`
	Yards      int32      `json:"yards"`
}

func (q *Queries) ListScoresByMatch(ctx context.Context, arg ListScoresByMatchParams) ([]ListScoresByMatchRow, error) {
	rows, err := q.db.Query(ctx, listScoresByMatch, arg.MatchID, arg.TenantID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListScoresByMatchRow{}
	for rows.Next() {
		var i ListScoresByMatchRow
		if err := rows.Scan(
			&i.ID,
			&i.MatchID,
			&i.TeamID,
			&i.PlayerID,
			&i.CourseID,
			&i.TeeColorID,
			&i.HoleNumber,
			&i.TenantID,
			&i.Strokes,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.Par,
			&i.HoleHdcp,
			&i.Yards,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const upsertPlayerScore = `-- name: UpsertPlayerScore :one
INSERT INTO scores (
    match_id, team_id, player_id, course_id, tee_color_id, hole_number, tenant_id, strokes
) VALUES (
    $1, $2, $3, $4, $5, $6, $7, $8
)
ON CONFLICT (match_id, hole_number, player_id) WHERE player_id IS NOT NULL
DO UPDATE SET strokes = EXCLUDED.strokes, updated_at = now()
RETURNING id, match_id, team_id, player_id, course_id, tee_color_id, hole_number, tenant_id, strokes, created_at, updated_at
`

type UpsertPlayerScoreParams struct {
	MatchID    uuid.UUID  `json:"match_id"`
	TeamID     uuid.UUID  `json:"team_id"`
	PlayerID   *uuid.UUID `json:"player_id"`
	CourseID   uuid.UUID  `json:"course_id"`
	TeeColorID uuid.UUID  `json:"tee_color_id"`
	HoleNumber int32      `json:"hole_number"`
	TenantID   uuid.UUID  `json:"tenant_id"`
	Strokes    int32      `json:"strokes"`
}

// Per-player score (singles / fourball): one row per player per hole.
func (q *Queries) UpsertPlayerScore(ctx context.Context, arg UpsertPlayerScoreParams) (Score, error) {
	row := q.db.QueryRow(ctx, upsertPlayerScore,
		arg.MatchID,
		arg.TeamID,
		arg.PlayerID,
		arg.CourseID,
		arg.TeeColorID,
		arg.HoleNumber,
		arg.TenantID,
		arg.Strokes,
	)
	var i Score
	err := row.Scan(
		&i.ID,
		&i.MatchID,
		&i.TeamID,
		&i.PlayerID,
		&i.CourseID,
		&i.TeeColorID,
		&i.HoleNumber,
		&i.TenantID,
		&i.Strokes,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const upsertTeamScore = `-- name: UpsertTeamScore :one
INSERT INTO scores (
    match_id, team_id, player_id, course_id, tee_color_id, hole_number, tenant_id, strokes
) VALUES (
    $1, $2, NULL, $3, $4, $5, $6, $7
)
ON CONFLICT (match_id, hole_number, team_id) WHERE player_id IS NULL
DO UPDATE SET strokes = EXCLUDED.strokes, updated_at = now()
RETURNING id, match_id, team_id, player_id, course_id, tee_color_id, hole_number, tenant_id, strokes, created_at, updated_at
`

type UpsertTeamScoreParams struct {
	MatchID    uuid.UUID `json:"match_id"`
	TeamID     uuid.UUID `json:"team_id"`
	CourseID   uuid.UUID `json:"course_id"`
	TeeColorID uuid.UUID `json:"tee_color_id"`
	HoleNumber int32     `json:"hole_number"`
	TenantID   uuid.UUID `json:"tenant_id"`
	Strokes    int32     `json:"strokes"`
}

// Team score (alternate shot / scramble / mod-scotch): one row per team per hole.
func (q *Queries) UpsertTeamScore(ctx context.Context, arg UpsertTeamScoreParams) (Score, error) {
	row := q.db.QueryRow(ctx, upsertTeamScore,
		arg.MatchID,
		arg.TeamID,
		arg.CourseID,
		arg.TeeColorID,
		arg.HoleNumber,
		arg.TenantID,
		arg.Strokes,
	)
	var i Score
	err := row.Scan(
		&i.ID,
		&i.MatchID,
		&i.TeamID,
		&i.PlayerID,
		&i.CourseID,
		&i.TeeColorID,
		&i.HoleNumber,
		&i.TenantID,
		&i.Strokes,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
