// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: team_members.sql

package sqlc

import (
	"context"

	"github.com/google/uuid"
)

const createTeamMember = `-- name: CreateTeamMember :one
INSERT INTO team_members (
    team_id,
    player_id,
    tournament_id,
    tenant_id,
    tier,
    biography,
    hdcp
) VALUES (
    $1, $2, $3, $4, $5, $6, $7
) RETURNING team_id, player_id, tournament_id, tenant_id, tier, biography, hdcp
`

type CreateTeamMemberParams struct {
	TeamID       int32     `json:"team_id"`
	PlayerID     int32     `json:"player_id"`
	TournamentID int32     `json:"tournament_id"`
	TenantID     uuid.UUID `json:"tenant_id"`
	Tier         string    `json:"tier"`
	Biography    string    `json:"biography"`
	Hdcp         float32   `json:"hdcp"`
}

func (q *Queries) CreateTeamMember(ctx context.Context, arg CreateTeamMemberParams) (TeamMember, error) {
	row := q.db.QueryRow(ctx, createTeamMember,
		arg.TeamID,
		arg.PlayerID,
		arg.TournamentID,
		arg.TenantID,
		arg.Tier,
		arg.Biography,
		arg.Hdcp,
	)
	var i TeamMember
	err := row.Scan(
		&i.TeamID,
		&i.PlayerID,
		&i.TournamentID,
		&i.TenantID,
		&i.Tier,
		&i.Biography,
		&i.Hdcp,
	)
	return i, err
}

const deleteTeamMember = `-- name: DeleteTeamMember :exec
DELETE FROM team_members
WHERE tournament_id = $1 AND player_id = $2 AND tenant_id = $3
`

type DeleteTeamMemberParams struct {
	TournamentID int32     `json:"tournament_id"`
	PlayerID     int32     `json:"player_id"`
	TenantID     uuid.UUID `json:"tenant_id"`
}

func (q *Queries) DeleteTeamMember(ctx context.Context, arg DeleteTeamMemberParams) error {
	_, err := q.db.Exec(ctx, deleteTeamMember, arg.TournamentID, arg.PlayerID, arg.TenantID)
	return err
}

const getTeamCaptain = `-- name: GetTeamCaptain :one
SELECT p.id, p.tenant_id, p.user_id, p.email, p.first_name, p.last_name, p.photo_path, p.created_at, p.updated_at
FROM teams t
JOIN players p ON t.captain_id = p.id
WHERE t.id = $1 AND t.tenant_id = $2
`

type GetTeamCaptainParams struct {
	ID       int32     `json:"id"`
	TenantID uuid.UUID `json:"tenant_id"`
}

func (q *Queries) GetTeamCaptain(ctx context.Context, arg GetTeamCaptainParams) (Player, error) {
	row := q.db.QueryRow(ctx, getTeamCaptain, arg.ID, arg.TenantID)
	var i Player
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.UserID,
		&i.Email,
		&i.FirstName,
		&i.LastName,
		&i.PhotoPath,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getTeamMember = `-- name: GetTeamMember :one
SELECT team_id, player_id, tournament_id, tenant_id, tier, biography, hdcp FROM team_members
WHERE tournament_id = $1 AND player_id = $2 AND tenant_id = $3
`

type GetTeamMemberParams struct {
	TournamentID int32     `json:"tournament_id"`
	PlayerID     int32     `json:"player_id"`
	TenantID     uuid.UUID `json:"tenant_id"`
}

func (q *Queries) GetTeamMember(ctx context.Context, arg GetTeamMemberParams) (TeamMember, error) {
	row := q.db.QueryRow(ctx, getTeamMember, arg.TournamentID, arg.PlayerID, arg.TenantID)
	var i TeamMember
	err := row.Scan(
		&i.TeamID,
		&i.PlayerID,
		&i.TournamentID,
		&i.TenantID,
		&i.Tier,
		&i.Biography,
		&i.Hdcp,
	)
	return i, err
}

const listTeamMembersByTeam = `-- name: ListTeamMembersByTeam :many
SELECT tm.team_id, tm.player_id, tm.tournament_id, tm.tenant_id, tm.tier, tm.biography, tm.hdcp, p.first_name, p.last_name, p.email
FROM team_members tm
JOIN players p ON tm.player_id = p.id
WHERE tm.team_id = $1 AND tm.tenant_id = $2
ORDER BY p.last_name, p.first_name
`

type ListTeamMembersByTeamParams struct {
	TeamID   int32     `json:"team_id"`
	TenantID uuid.UUID `json:"tenant_id"`
}

type ListTeamMembersByTeamRow struct {
	TeamID       int32     `json:"team_id"`
	PlayerID     int32     `json:"player_id"`
	TournamentID int32     `json:"tournament_id"`
	TenantID     uuid.UUID `json:"tenant_id"`
	Tier         string    `json:"tier"`
	Biography    string    `json:"biography"`
	Hdcp         float32   `json:"hdcp"`
	FirstName    string    `json:"first_name"`
	LastName     string    `json:"last_name"`
	Email        *string   `json:"email"`
}

func (q *Queries) ListTeamMembersByTeam(ctx context.Context, arg ListTeamMembersByTeamParams) ([]ListTeamMembersByTeamRow, error) {
	rows, err := q.db.Query(ctx, listTeamMembersByTeam, arg.TeamID, arg.TenantID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListTeamMembersByTeamRow{}
	for rows.Next() {
		var i ListTeamMembersByTeamRow
		if err := rows.Scan(
			&i.TeamID,
			&i.PlayerID,
			&i.TournamentID,
			&i.TenantID,
			&i.Tier,
			&i.Biography,
			&i.Hdcp,
			&i.FirstName,
			&i.LastName,
			&i.Email,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listTeamMembersByTournament = `-- name: ListTeamMembersByTournament :many
SELECT tm.team_id, tm.player_id, tm.tournament_id, tm.tenant_id, tm.tier, tm.biography, tm.hdcp, p.first_name, p.last_name, p.email, t.color AS team_color
FROM team_members tm
JOIN players p ON tm.player_id = p.id
JOIN teams t ON tm.team_id = t.id
WHERE tm.tournament_id = $1 AND tm.tenant_id = $2
ORDER BY t.color, p.last_name, p.first_name
`

type ListTeamMembersByTournamentParams struct {
	TournamentID int32     `json:"tournament_id"`
	TenantID     uuid.UUID `json:"tenant_id"`
}

type ListTeamMembersByTournamentRow struct {
	TeamID       int32     `json:"team_id"`
	PlayerID     int32     `json:"player_id"`
	TournamentID int32     `json:"tournament_id"`
	TenantID     uuid.UUID `json:"tenant_id"`
	Tier         string    `json:"tier"`
	Biography    string    `json:"biography"`
	Hdcp         float32   `json:"hdcp"`
	FirstName    string    `json:"first_name"`
	LastName     string    `json:"last_name"`
	Email        *string   `json:"email"`
	TeamColor    string    `json:"team_color"`
}

func (q *Queries) ListTeamMembersByTournament(ctx context.Context, arg ListTeamMembersByTournamentParams) ([]ListTeamMembersByTournamentRow, error) {
	rows, err := q.db.Query(ctx, listTeamMembersByTournament, arg.TournamentID, arg.TenantID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListTeamMembersByTournamentRow{}
	for rows.Next() {
		var i ListTeamMembersByTournamentRow
		if err := rows.Scan(
			&i.TeamID,
			&i.PlayerID,
			&i.TournamentID,
			&i.TenantID,
			&i.Tier,
			&i.Biography,
			&i.Hdcp,
			&i.FirstName,
			&i.LastName,
			&i.Email,
			&i.TeamColor,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateTeamMember = `-- name: UpdateTeamMember :one
UPDATE team_members
SET tier = $4, biography = $5, hdcp = $6
WHERE team_id = $1 AND player_id = $2 AND tenant_id = $3
RETURNING team_id, player_id, tournament_id, tenant_id, tier, biography, hdcp
`

type UpdateTeamMemberParams struct {
	TeamID    int32     `json:"team_id"`
	PlayerID  int32     `json:"player_id"`
	TenantID  uuid.UUID `json:"tenant_id"`
	Tier      string    `json:"tier"`
	Biography string    `json:"biography"`
	Hdcp      float32   `json:"hdcp"`
}

func (q *Queries) UpdateTeamMember(ctx context.Context, arg UpdateTeamMemberParams) (TeamMember, error) {
	row := q.db.QueryRow(ctx, updateTeamMember,
		arg.TeamID,
		arg.PlayerID,
		arg.TenantID,
		arg.Tier,
		arg.Biography,
		arg.Hdcp,
	)
	var i TeamMember
	err := row.Scan(
		&i.TeamID,
		&i.PlayerID,
		&i.TournamentID,
		&i.TenantID,
		&i.Tier,
		&i.Biography,
		&i.Hdcp,
	)
	return i, err
}
