// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: teams.sql

package sqlc

import (
	"context"

	"github.com/google/uuid"
)

const clearTeamCaptain = `-- name: ClearTeamCaptain :execrows
UPDATE teams
SET captain_id = NULL
WHERE id = $1 AND tenant_id = $2
`

type ClearTeamCaptainParams struct {
	ID       uuid.UUID `json:"id"`
	TenantID uuid.UUID `json:"tenant_id"`
}

// Unset a team's captain outright (used to reassign). Rows affected = 0 only when the
// team doesn't exist, which the caller turns into a 404.
func (q *Queries) ClearTeamCaptain(ctx context.Context, arg ClearTeamCaptainParams) (int64, error) {
	result, err := q.db.Exec(ctx, clearTeamCaptain, arg.ID, arg.TenantID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const clearTeamCaptainForPlayer = `-- name: ClearTeamCaptainForPlayer :exec
UPDATE teams
SET captain_id = NULL
WHERE id = $1 AND captain_id = $2 AND tenant_id = $3
`

type ClearTeamCaptainForPlayerParams struct {
	ID        uuid.UUID  `json:"id"`
	CaptainID *uuid.UUID `json:"captain_id"`
	TenantID  uuid.UUID  `json:"tenant_id"`
}

// Clears the captain when that player leaves the team (e.g. undrafted), so a team never
// keeps a captain who is no longer on it. A no-op when the player wasn't the captain.
func (q *Queries) ClearTeamCaptainForPlayer(ctx context.Context, arg ClearTeamCaptainForPlayerParams) error {
	_, err := q.db.Exec(ctx, clearTeamCaptainForPlayer, arg.ID, arg.CaptainID, arg.TenantID)
	return err
}

const createTeam = `-- name: CreateTeam :one
INSERT INTO teams (
    tenant_id,
    tournament_id,
    color,
    captain_id
) VALUES (
    $1, $2, $3, $4
) RETURNING id, tenant_id, tournament_id, color, captain_id
`

type CreateTeamParams struct {
	TenantID     uuid.UUID  `json:"tenant_id"`
	TournamentID uuid.UUID  `json:"tournament_id"`
	Color        string     `json:"color"`
	CaptainID    *uuid.UUID `json:"captain_id"`
}

func (q *Queries) CreateTeam(ctx context.Context, arg CreateTeamParams) (Team, error) {
	row := q.db.QueryRow(ctx, createTeam,
		arg.TenantID,
		arg.TournamentID,
		arg.Color,
		arg.CaptainID,
	)
	var i Team
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.TournamentID,
		&i.Color,
		&i.CaptainID,
	)
	return i, err
}

const getTeam = `-- name: GetTeam :one
SELECT id, tenant_id, tournament_id, color, captain_id FROM teams
WHERE id = $1 AND tenant_id = $2
`

type GetTeamParams struct {
	ID       uuid.UUID `json:"id"`
	TenantID uuid.UUID `json:"tenant_id"`
}

func (q *Queries) GetTeam(ctx context.Context, arg GetTeamParams) (Team, error) {
	row := q.db.QueryRow(ctx, getTeam, arg.ID, arg.TenantID)
	var i Team
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.TournamentID,
		&i.Color,
		&i.CaptainID,
	)
	return i, err
}

const listAllTeams = `-- name: ListAllTeams :many
SELECT tournament_id, id AS team_id FROM teams
WHERE tenant_id = $1
`

type ListAllTeamsRow struct {
	TournamentID uuid.UUID `json:"tournament_id"`
	TeamID       uuid.UUID `json:"team_id"`
}

// Every team by tournament, so the domain can settle each Cup's winner.
func (q *Queries) ListAllTeams(ctx context.Context, tenantID uuid.UUID) ([]ListAllTeamsRow, error) {
	rows, err := q.db.Query(ctx, listAllTeams, tenantID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListAllTeamsRow{}
	for rows.Next() {
		var i ListAllTeamsRow
		if err := rows.Scan(&i.TournamentID, &i.TeamID); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listTeamsByTournament = `-- name: ListTeamsByTournament :many
SELECT
    t.id, t.tenant_id, t.tournament_id, t.color, t.captain_id,
    p.first_name AS captain_first_name,
    p.last_name  AS captain_last_name
FROM teams t
LEFT JOIN players p ON p.id = t.captain_id
WHERE t.tournament_id = $1 AND t.tenant_id = $2
ORDER BY t.color
`

type ListTeamsByTournamentParams struct {
	TournamentID uuid.UUID `json:"tournament_id"`
	TenantID     uuid.UUID `json:"tenant_id"`
}

type ListTeamsByTournamentRow struct {
	ID               uuid.UUID  `json:"id"`
	TenantID         uuid.UUID  `json:"tenant_id"`
	TournamentID     uuid.UUID  `json:"tournament_id"`
	Color            string     `json:"color"`
	CaptainID        *uuid.UUID `json:"captain_id"`
	CaptainFirstName *string    `json:"captain_first_name"`
	CaptainLastName  *string    `json:"captain_last_name"`
}

// LEFT JOIN so the captain (if any) comes back in one query instead of a per-team lookup.
func (q *Queries) ListTeamsByTournament(ctx context.Context, arg ListTeamsByTournamentParams) ([]ListTeamsByTournamentRow, error) {
	rows, err := q.db.Query(ctx, listTeamsByTournament, arg.TournamentID, arg.TenantID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListTeamsByTournamentRow{}
	for rows.Next() {
		var i ListTeamsByTournamentRow
		if err := rows.Scan(
			&i.ID,
			&i.TenantID,
			&i.TournamentID,
			&i.Color,
			&i.CaptainID,
			&i.CaptainFirstName,
			&i.CaptainLastName,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const setTeamCaptain = `-- name: SetTeamCaptain :one
UPDATE teams
SET captain_id = $3
WHERE id = $1 AND tenant_id = $2
RETURNING id, tenant_id, tournament_id, color, captain_id
`

type SetTeamCaptainParams struct {
	ID        uuid.UUID  `json:"id"`
	TenantID  uuid.UUID  `json:"tenant_id"`
	CaptainID *uuid.UUID `json:"captain_id"`
}

func (q *Queries) SetTeamCaptain(ctx context.Context, arg SetTeamCaptainParams) (Team, error) {
	row := q.db.QueryRow(ctx, setTeamCaptain, arg.ID, arg.TenantID, arg.CaptainID)
	var i Team
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.TournamentID,
		&i.Color,
		&i.CaptainID,
	)
	return i, err
}
