// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: team_members.sql

package sqlc

import (
	"context"

	"github.com/google/uuid"
)

const createTeamMember = `-- name: CreateTeamMember :one

INSERT INTO team_members (
    team_id,
    player_id,
    tournament_id,
    tenant_id
) VALUES (
    $1, $2, $3, $4
) RETURNING team_id, player_id, tournament_id, tenant_id
`

type CreateTeamMemberParams struct {
	TeamID       uuid.UUID `json:"team_id"`
	PlayerID     uuid.UUID `json:"player_id"`
	TournamentID uuid.UUID `json:"tournament_id"`
	TenantID     uuid.UUID `json:"tenant_id"`
}

// team_members records the draft: an entered player assigned to a team. Per-tournament
// attributes (tier/biography/hdcp) live on tournament_players. Roster listings are
// served from the tournament_players queries (which carry the team assignment).
func (q *Queries) CreateTeamMember(ctx context.Context, arg CreateTeamMemberParams) (TeamMember, error) {
	row := q.db.QueryRow(ctx, createTeamMember,
		arg.TeamID,
		arg.PlayerID,
		arg.TournamentID,
		arg.TenantID,
	)
	var i TeamMember
	err := row.Scan(
		&i.TeamID,
		&i.PlayerID,
		&i.TournamentID,
		&i.TenantID,
	)
	return i, err
}

const deleteTeamMember = `-- name: DeleteTeamMember :exec
DELETE FROM team_members
WHERE tournament_id = $1 AND player_id = $2 AND tenant_id = $3
`

type DeleteTeamMemberParams struct {
	TournamentID uuid.UUID `json:"tournament_id"`
	PlayerID     uuid.UUID `json:"player_id"`
	TenantID     uuid.UUID `json:"tenant_id"`
}

func (q *Queries) DeleteTeamMember(ctx context.Context, arg DeleteTeamMemberParams) error {
	_, err := q.db.Exec(ctx, deleteTeamMember, arg.TournamentID, arg.PlayerID, arg.TenantID)
	return err
}

const getTeamCaptain = `-- name: GetTeamCaptain :one
SELECT p.id, p.tenant_id, p.user_id, p.email, p.first_name, p.last_name, p.photo_path, p.created_at, p.updated_at
FROM teams t
JOIN players p ON t.captain_id = p.id
WHERE t.id = $1 AND t.tenant_id = $2
`

type GetTeamCaptainParams struct {
	ID       uuid.UUID `json:"id"`
	TenantID uuid.UUID `json:"tenant_id"`
}

func (q *Queries) GetTeamCaptain(ctx context.Context, arg GetTeamCaptainParams) (Player, error) {
	row := q.db.QueryRow(ctx, getTeamCaptain, arg.ID, arg.TenantID)
	var i Player
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.UserID,
		&i.Email,
		&i.FirstName,
		&i.LastName,
		&i.PhotoPath,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getTeamMember = `-- name: GetTeamMember :one
SELECT team_id, player_id, tournament_id, tenant_id FROM team_members
WHERE tournament_id = $1 AND player_id = $2 AND tenant_id = $3
`

type GetTeamMemberParams struct {
	TournamentID uuid.UUID `json:"tournament_id"`
	PlayerID     uuid.UUID `json:"player_id"`
	TenantID     uuid.UUID `json:"tenant_id"`
}

func (q *Queries) GetTeamMember(ctx context.Context, arg GetTeamMemberParams) (TeamMember, error) {
	row := q.db.QueryRow(ctx, getTeamMember, arg.TournamentID, arg.PlayerID, arg.TenantID)
	var i TeamMember
	err := row.Scan(
		&i.TeamID,
		&i.PlayerID,
		&i.TournamentID,
		&i.TenantID,
	)
	return i, err
}
