// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: teams.sql

package sqlc

import (
	"context"

	"github.com/google/uuid"
)

const createTeam = `-- name: CreateTeam :one
INSERT INTO teams (
    tenant_id,
    name
) VALUES (
    $1, $2
) RETURNING id, tenant_id, name
`

type CreateTeamParams struct {
	TenantID uuid.UUID `json:"tenant_id"`
	Name     string    `json:"name"`
}

func (q *Queries) CreateTeam(ctx context.Context, arg CreateTeamParams) (Team, error) {
	row := q.db.QueryRow(ctx, createTeam, arg.TenantID, arg.Name)
	var i Team
	err := row.Scan(&i.ID, &i.TenantID, &i.Name)
	return i, err
}

const deleteTeam = `-- name: DeleteTeam :exec
DELETE FROM teams
WHERE id = $1 AND tenant_id = $2
`

type DeleteTeamParams struct {
	ID       int32     `json:"id"`
	TenantID uuid.UUID `json:"tenant_id"`
}

func (q *Queries) DeleteTeam(ctx context.Context, arg DeleteTeamParams) error {
	_, err := q.db.Exec(ctx, deleteTeam, arg.ID, arg.TenantID)
	return err
}

const getTeam = `-- name: GetTeam :one
SELECT id, tenant_id, name FROM teams
WHERE id = $1 AND tenant_id = $2
`

type GetTeamParams struct {
	ID       int32     `json:"id"`
	TenantID uuid.UUID `json:"tenant_id"`
}

func (q *Queries) GetTeam(ctx context.Context, arg GetTeamParams) (Team, error) {
	row := q.db.QueryRow(ctx, getTeam, arg.ID, arg.TenantID)
	var i Team
	err := row.Scan(&i.ID, &i.TenantID, &i.Name)
	return i, err
}

const getTeamByName = `-- name: GetTeamByName :one
SELECT id, tenant_id, name FROM teams
WHERE name = $1 AND tenant_id = $2
`

type GetTeamByNameParams struct {
	Name     string    `json:"name"`
	TenantID uuid.UUID `json:"tenant_id"`
}

func (q *Queries) GetTeamByName(ctx context.Context, arg GetTeamByNameParams) (Team, error) {
	row := q.db.QueryRow(ctx, getTeamByName, arg.Name, arg.TenantID)
	var i Team
	err := row.Scan(&i.ID, &i.TenantID, &i.Name)
	return i, err
}

const listTeams = `-- name: ListTeams :many
SELECT id, tenant_id, name FROM teams
WHERE tenant_id = $1
ORDER BY name
`

func (q *Queries) ListTeams(ctx context.Context, tenantID uuid.UUID) ([]Team, error) {
	rows, err := q.db.Query(ctx, listTeams, tenantID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Team{}
	for rows.Next() {
		var i Team
		if err := rows.Scan(&i.ID, &i.TenantID, &i.Name); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateTeam = `-- name: UpdateTeam :one
UPDATE teams
SET name = $3
WHERE id = $1 AND tenant_id = $2
RETURNING id, tenant_id, name
`

type UpdateTeamParams struct {
	ID       int32     `json:"id"`
	TenantID uuid.UUID `json:"tenant_id"`
	Name     string    `json:"name"`
}

func (q *Queries) UpdateTeam(ctx context.Context, arg UpdateTeamParams) (Team, error) {
	row := q.db.QueryRow(ctx, updateTeam, arg.ID, arg.TenantID, arg.Name)
	var i Team
	err := row.Scan(&i.ID, &i.TenantID, &i.Name)
	return i, err
}
