// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: teams.sql

package sqlc

import (
	"context"

	"github.com/google/uuid"
)

const createTeam = `-- name: CreateTeam :one
INSERT INTO teams (
    tenant_id,
    tournament_id,
    color,
    captain_id
) VALUES (
    $1, $2, $3, $4
) RETURNING id, tenant_id, tournament_id, color, captain_id
`

type CreateTeamParams struct {
	TenantID     uuid.UUID `json:"tenant_id"`
	TournamentID int32     `json:"tournament_id"`
	Color        string    `json:"color"`
	CaptainID    *int32    `json:"captain_id"`
}

func (q *Queries) CreateTeam(ctx context.Context, arg CreateTeamParams) (Team, error) {
	row := q.db.QueryRow(ctx, createTeam,
		arg.TenantID,
		arg.TournamentID,
		arg.Color,
		arg.CaptainID,
	)
	var i Team
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.TournamentID,
		&i.Color,
		&i.CaptainID,
	)
	return i, err
}

const deleteTeam = `-- name: DeleteTeam :exec
DELETE FROM teams
WHERE id = $1 AND tenant_id = $2
`

type DeleteTeamParams struct {
	ID       int32     `json:"id"`
	TenantID uuid.UUID `json:"tenant_id"`
}

func (q *Queries) DeleteTeam(ctx context.Context, arg DeleteTeamParams) error {
	_, err := q.db.Exec(ctx, deleteTeam, arg.ID, arg.TenantID)
	return err
}

const getTeam = `-- name: GetTeam :one
SELECT id, tenant_id, tournament_id, color, captain_id FROM teams
WHERE id = $1 AND tenant_id = $2
`

type GetTeamParams struct {
	ID       int32     `json:"id"`
	TenantID uuid.UUID `json:"tenant_id"`
}

func (q *Queries) GetTeam(ctx context.Context, arg GetTeamParams) (Team, error) {
	row := q.db.QueryRow(ctx, getTeam, arg.ID, arg.TenantID)
	var i Team
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.TournamentID,
		&i.Color,
		&i.CaptainID,
	)
	return i, err
}

const getTeamByColor = `-- name: GetTeamByColor :one
SELECT id, tenant_id, tournament_id, color, captain_id FROM teams
WHERE tournament_id = $1 AND color = $2 AND tenant_id = $3
`

type GetTeamByColorParams struct {
	TournamentID int32     `json:"tournament_id"`
	Color        string    `json:"color"`
	TenantID     uuid.UUID `json:"tenant_id"`
}

func (q *Queries) GetTeamByColor(ctx context.Context, arg GetTeamByColorParams) (Team, error) {
	row := q.db.QueryRow(ctx, getTeamByColor, arg.TournamentID, arg.Color, arg.TenantID)
	var i Team
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.TournamentID,
		&i.Color,
		&i.CaptainID,
	)
	return i, err
}

const listTeamsByTournament = `-- name: ListTeamsByTournament :many
SELECT id, tenant_id, tournament_id, color, captain_id FROM teams
WHERE tournament_id = $1 AND tenant_id = $2
ORDER BY color
`

type ListTeamsByTournamentParams struct {
	TournamentID int32     `json:"tournament_id"`
	TenantID     uuid.UUID `json:"tenant_id"`
}

func (q *Queries) ListTeamsByTournament(ctx context.Context, arg ListTeamsByTournamentParams) ([]Team, error) {
	rows, err := q.db.Query(ctx, listTeamsByTournament, arg.TournamentID, arg.TenantID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Team{}
	for rows.Next() {
		var i Team
		if err := rows.Scan(
			&i.ID,
			&i.TenantID,
			&i.TournamentID,
			&i.Color,
			&i.CaptainID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const setTeamCaptain = `-- name: SetTeamCaptain :one
UPDATE teams
SET captain_id = $3
WHERE id = $1 AND tenant_id = $2
RETURNING id, tenant_id, tournament_id, color, captain_id
`

type SetTeamCaptainParams struct {
	ID        int32     `json:"id"`
	TenantID  uuid.UUID `json:"tenant_id"`
	CaptainID *int32    `json:"captain_id"`
}

func (q *Queries) SetTeamCaptain(ctx context.Context, arg SetTeamCaptainParams) (Team, error) {
	row := q.db.QueryRow(ctx, setTeamCaptain, arg.ID, arg.TenantID, arg.CaptainID)
	var i Team
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.TournamentID,
		&i.Color,
		&i.CaptainID,
	)
	return i, err
}
