// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: team_members.sql

package sqlc

import (
	"context"

	"github.com/google/uuid"
)

const createTeamMember = `-- name: CreateTeamMember :one

INSERT INTO team_members (
    team_id,
    player_id,
    tournament_id,
    tenant_id
) VALUES (
    $1, $2, $3, $4
) RETURNING team_id, player_id, tournament_id, tenant_id
`

type CreateTeamMemberParams struct {
	TeamID       uuid.UUID `json:"team_id"`
	PlayerID     uuid.UUID `json:"player_id"`
	TournamentID uuid.UUID `json:"tournament_id"`
	TenantID     uuid.UUID `json:"tenant_id"`
}

// team_members records the draft: an entered player assigned to a team. Per-tournament
// attributes (tier/biography/hdcp) live on tournament_players. Roster listings are
// served from the tournament_players queries (which carry the team assignment).
func (q *Queries) CreateTeamMember(ctx context.Context, arg CreateTeamMemberParams) (TeamMember, error) {
	row := q.db.QueryRow(ctx, createTeamMember,
		arg.TeamID,
		arg.PlayerID,
		arg.TournamentID,
		arg.TenantID,
	)
	var i TeamMember
	err := row.Scan(
		&i.TeamID,
		&i.PlayerID,
		&i.TournamentID,
		&i.TenantID,
	)
	return i, err
}

const deleteTeamMember = `-- name: DeleteTeamMember :execrows
DELETE FROM team_members
WHERE team_id = $1 AND player_id = $2 AND tenant_id = $3
`

type DeleteTeamMemberParams struct {
	TeamID   uuid.UUID `json:"team_id"`
	PlayerID uuid.UUID `json:"player_id"`
	TenantID uuid.UUID `json:"tenant_id"`
}

// Undraft a player. ON DELETE CASCADE pulls them from any match_participants too.
func (q *Queries) DeleteTeamMember(ctx context.Context, arg DeleteTeamMemberParams) (int64, error) {
	result, err := q.db.Exec(ctx, deleteTeamMember, arg.TeamID, arg.PlayerID, arg.TenantID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}
