// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: tee_sets.sql

package sqlc

import (
	"context"

	"github.com/google/uuid"
)

const createTeeSet = `-- name: CreateTeeSet :one
INSERT INTO tee_sets (
    course_id,
    tee_color_id,
    tenant_id,
    slope,
    rating
) VALUES (
    $1, $2, $3, $4, $5
) RETURNING course_id, tee_color_id, tenant_id, slope, rating
`

type CreateTeeSetParams struct {
	CourseID   int32     `json:"course_id"`
	TeeColorID int32     `json:"tee_color_id"`
	TenantID   uuid.UUID `json:"tenant_id"`
	Slope      int32     `json:"slope"`
	Rating     float64   `json:"rating"`
}

func (q *Queries) CreateTeeSet(ctx context.Context, arg CreateTeeSetParams) (TeeSet, error) {
	row := q.db.QueryRow(ctx, createTeeSet,
		arg.CourseID,
		arg.TeeColorID,
		arg.TenantID,
		arg.Slope,
		arg.Rating,
	)
	var i TeeSet
	err := row.Scan(
		&i.CourseID,
		&i.TeeColorID,
		&i.TenantID,
		&i.Slope,
		&i.Rating,
	)
	return i, err
}

const deleteTeeSet = `-- name: DeleteTeeSet :exec
DELETE FROM tee_sets
WHERE course_id = $1 AND tee_color_id = $2 AND tenant_id = $3
`

type DeleteTeeSetParams struct {
	CourseID   int32     `json:"course_id"`
	TeeColorID int32     `json:"tee_color_id"`
	TenantID   uuid.UUID `json:"tenant_id"`
}

func (q *Queries) DeleteTeeSet(ctx context.Context, arg DeleteTeeSetParams) error {
	_, err := q.db.Exec(ctx, deleteTeeSet, arg.CourseID, arg.TeeColorID, arg.TenantID)
	return err
}

const getTeeSet = `-- name: GetTeeSet :one
SELECT course_id, tee_color_id, tenant_id, slope, rating FROM tee_sets
WHERE course_id = $1 AND tee_color_id = $2 AND tenant_id = $3
`

type GetTeeSetParams struct {
	CourseID   int32     `json:"course_id"`
	TeeColorID int32     `json:"tee_color_id"`
	TenantID   uuid.UUID `json:"tenant_id"`
}

func (q *Queries) GetTeeSet(ctx context.Context, arg GetTeeSetParams) (TeeSet, error) {
	row := q.db.QueryRow(ctx, getTeeSet, arg.CourseID, arg.TeeColorID, arg.TenantID)
	var i TeeSet
	err := row.Scan(
		&i.CourseID,
		&i.TeeColorID,
		&i.TenantID,
		&i.Slope,
		&i.Rating,
	)
	return i, err
}

const listTeeSetsByCourse = `-- name: ListTeeSetsByCourse :many
SELECT ts.course_id, ts.tee_color_id, ts.tenant_id, ts.slope, ts.rating, tc.color as tee_color_name
FROM tee_sets ts
JOIN tee_colors tc ON ts.tee_color_id = tc.id
WHERE ts.course_id = $1 AND ts.tenant_id = $2
ORDER BY tc.color
`

type ListTeeSetsByCourseParams struct {
	CourseID int32     `json:"course_id"`
	TenantID uuid.UUID `json:"tenant_id"`
}

type ListTeeSetsByCourseRow struct {
	CourseID     int32     `json:"course_id"`
	TeeColorID   int32     `json:"tee_color_id"`
	TenantID     uuid.UUID `json:"tenant_id"`
	Slope        int32     `json:"slope"`
	Rating       float64   `json:"rating"`
	TeeColorName string    `json:"tee_color_name"`
}

func (q *Queries) ListTeeSetsByCourse(ctx context.Context, arg ListTeeSetsByCourseParams) ([]ListTeeSetsByCourseRow, error) {
	rows, err := q.db.Query(ctx, listTeeSetsByCourse, arg.CourseID, arg.TenantID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListTeeSetsByCourseRow{}
	for rows.Next() {
		var i ListTeeSetsByCourseRow
		if err := rows.Scan(
			&i.CourseID,
			&i.TeeColorID,
			&i.TenantID,
			&i.Slope,
			&i.Rating,
			&i.TeeColorName,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateTeeSet = `-- name: UpdateTeeSet :one
UPDATE tee_sets
SET
    slope = $4,
    rating = $5
WHERE course_id = $1 AND tee_color_id = $2 AND tenant_id = $3
RETURNING course_id, tee_color_id, tenant_id, slope, rating
`

type UpdateTeeSetParams struct {
	CourseID   int32     `json:"course_id"`
	TeeColorID int32     `json:"tee_color_id"`
	TenantID   uuid.UUID `json:"tenant_id"`
	Slope      int32     `json:"slope"`
	Rating     float64   `json:"rating"`
}

func (q *Queries) UpdateTeeSet(ctx context.Context, arg UpdateTeeSetParams) (TeeSet, error) {
	row := q.db.QueryRow(ctx, updateTeeSet,
		arg.CourseID,
		arg.TeeColorID,
		arg.TenantID,
		arg.Slope,
		arg.Rating,
	)
	var i TeeSet
	err := row.Scan(
		&i.CourseID,
		&i.TeeColorID,
		&i.TenantID,
		&i.Slope,
		&i.Rating,
	)
	return i, err
}
