// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: tee_sets.sql

package sqlc

import (
	"context"

	"github.com/google/uuid"
)

const createTeeSet = `-- name: CreateTeeSet :one
INSERT INTO tee_sets (
    course_id,
    tee_color_id,
    tenant_id,
    slope,
    rating
) VALUES (
    $1, $2, $3, $4, $5
) RETURNING course_id, tee_color_id, tenant_id, slope, rating
`

type CreateTeeSetParams struct {
	CourseID   uuid.UUID `json:"course_id"`
	TeeColorID uuid.UUID `json:"tee_color_id"`
	TenantID   uuid.UUID `json:"tenant_id"`
	Slope      int32     `json:"slope"`
	Rating     float64   `json:"rating"`
}

func (q *Queries) CreateTeeSet(ctx context.Context, arg CreateTeeSetParams) (TeeSet, error) {
	row := q.db.QueryRow(ctx, createTeeSet,
		arg.CourseID,
		arg.TeeColorID,
		arg.TenantID,
		arg.Slope,
		arg.Rating,
	)
	var i TeeSet
	err := row.Scan(
		&i.CourseID,
		&i.TeeColorID,
		&i.TenantID,
		&i.Slope,
		&i.Rating,
	)
	return i, err
}
