// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: tournament_players.sql

package sqlc

import (
	"context"
	"time"

	"github.com/google/uuid"
)

const createTournamentPlayer = `-- name: CreateTournamentPlayer :one

INSERT INTO tournament_players (
    tournament_id,
    player_id,
    tenant_id,
    tier,
    biography,
    hdcp
) VALUES (
    $1, $2, $3, $4, $5, $6
) RETURNING tournament_id, player_id, tenant_id, tier, biography, hdcp, created_at, updated_at
`

type CreateTournamentPlayerParams struct {
	TournamentID int32     `json:"tournament_id"`
	PlayerID     int32     `json:"player_id"`
	TenantID     uuid.UUID `json:"tenant_id"`
	Tier         string    `json:"tier"`
	Biography    string    `json:"biography"`
	Hdcp         float32   `json:"hdcp"`
}

// tournament_players holds a player's per-tournament attributes (tier, biography,
// handicap), set independently of the team draft.
func (q *Queries) CreateTournamentPlayer(ctx context.Context, arg CreateTournamentPlayerParams) (TournamentPlayer, error) {
	row := q.db.QueryRow(ctx, createTournamentPlayer,
		arg.TournamentID,
		arg.PlayerID,
		arg.TenantID,
		arg.Tier,
		arg.Biography,
		arg.Hdcp,
	)
	var i TournamentPlayer
	err := row.Scan(
		&i.TournamentID,
		&i.PlayerID,
		&i.TenantID,
		&i.Tier,
		&i.Biography,
		&i.Hdcp,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteTournamentPlayer = `-- name: DeleteTournamentPlayer :exec
DELETE FROM tournament_players
WHERE tournament_id = $1 AND player_id = $2 AND tenant_id = $3
`

type DeleteTournamentPlayerParams struct {
	TournamentID int32     `json:"tournament_id"`
	PlayerID     int32     `json:"player_id"`
	TenantID     uuid.UUID `json:"tenant_id"`
}

func (q *Queries) DeleteTournamentPlayer(ctx context.Context, arg DeleteTournamentPlayerParams) error {
	_, err := q.db.Exec(ctx, deleteTournamentPlayer, arg.TournamentID, arg.PlayerID, arg.TenantID)
	return err
}

const getTournamentPlayer = `-- name: GetTournamentPlayer :one
SELECT tournament_id, player_id, tenant_id, tier, biography, hdcp, created_at, updated_at FROM tournament_players
WHERE tournament_id = $1 AND player_id = $2 AND tenant_id = $3
`

type GetTournamentPlayerParams struct {
	TournamentID int32     `json:"tournament_id"`
	PlayerID     int32     `json:"player_id"`
	TenantID     uuid.UUID `json:"tenant_id"`
}

func (q *Queries) GetTournamentPlayer(ctx context.Context, arg GetTournamentPlayerParams) (TournamentPlayer, error) {
	row := q.db.QueryRow(ctx, getTournamentPlayer, arg.TournamentID, arg.PlayerID, arg.TenantID)
	var i TournamentPlayer
	err := row.Scan(
		&i.TournamentID,
		&i.PlayerID,
		&i.TenantID,
		&i.Tier,
		&i.Biography,
		&i.Hdcp,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listTournamentPlayers = `-- name: ListTournamentPlayers :many
SELECT tp.tournament_id, tp.player_id, tp.tenant_id, tp.tier, tp.biography, tp.hdcp, tp.created_at, tp.updated_at, p.first_name, p.last_name, p.email, p.photo_path
FROM tournament_players tp
JOIN players p ON tp.player_id = p.id
WHERE tp.tournament_id = $1 AND tp.tenant_id = $2
ORDER BY p.last_name, p.first_name
`

type ListTournamentPlayersParams struct {
	TournamentID int32     `json:"tournament_id"`
	TenantID     uuid.UUID `json:"tenant_id"`
}

type ListTournamentPlayersRow struct {
	TournamentID int32     `json:"tournament_id"`
	PlayerID     int32     `json:"player_id"`
	TenantID     uuid.UUID `json:"tenant_id"`
	Tier         string    `json:"tier"`
	Biography    string    `json:"biography"`
	Hdcp         float32   `json:"hdcp"`
	CreatedAt    time.Time `json:"created_at"`
	UpdatedAt    time.Time `json:"updated_at"`
	FirstName    string    `json:"first_name"`
	LastName     string    `json:"last_name"`
	Email        *string   `json:"email"`
	PhotoPath    string    `json:"photo_path"`
}

func (q *Queries) ListTournamentPlayers(ctx context.Context, arg ListTournamentPlayersParams) ([]ListTournamentPlayersRow, error) {
	rows, err := q.db.Query(ctx, listTournamentPlayers, arg.TournamentID, arg.TenantID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListTournamentPlayersRow{}
	for rows.Next() {
		var i ListTournamentPlayersRow
		if err := rows.Scan(
			&i.TournamentID,
			&i.PlayerID,
			&i.TenantID,
			&i.Tier,
			&i.Biography,
			&i.Hdcp,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.FirstName,
			&i.LastName,
			&i.Email,
			&i.PhotoPath,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateTournamentPlayer = `-- name: UpdateTournamentPlayer :one
UPDATE tournament_players
SET tier = $4, biography = $5, hdcp = $6, updated_at = now()
WHERE tournament_id = $1 AND player_id = $2 AND tenant_id = $3
RETURNING tournament_id, player_id, tenant_id, tier, biography, hdcp, created_at, updated_at
`

type UpdateTournamentPlayerParams struct {
	TournamentID int32     `json:"tournament_id"`
	PlayerID     int32     `json:"player_id"`
	TenantID     uuid.UUID `json:"tenant_id"`
	Tier         string    `json:"tier"`
	Biography    string    `json:"biography"`
	Hdcp         float32   `json:"hdcp"`
}

func (q *Queries) UpdateTournamentPlayer(ctx context.Context, arg UpdateTournamentPlayerParams) (TournamentPlayer, error) {
	row := q.db.QueryRow(ctx, updateTournamentPlayer,
		arg.TournamentID,
		arg.PlayerID,
		arg.TenantID,
		arg.Tier,
		arg.Biography,
		arg.Hdcp,
	)
	var i TournamentPlayer
	err := row.Scan(
		&i.TournamentID,
		&i.PlayerID,
		&i.TenantID,
		&i.Tier,
		&i.Biography,
		&i.Hdcp,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
