// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: tournaments.sql

package sqlc

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const createTournament = `-- name: CreateTournament :one
INSERT INTO tournaments (
    tenant_id,
    name,
    start_date,
    end_date,
    location
) VALUES (
    $1, $2, $3, $4, $5
) RETURNING id, tenant_id, name, start_date, end_date, location
`

type CreateTournamentParams struct {
	TenantID  uuid.UUID   `json:"tenant_id"`
	Name      string      `json:"name"`
	StartDate pgtype.Date `json:"start_date"`
	EndDate   pgtype.Date `json:"end_date"`
	Location  string      `json:"location"`
}

func (q *Queries) CreateTournament(ctx context.Context, arg CreateTournamentParams) (Tournament, error) {
	row := q.db.QueryRow(ctx, createTournament,
		arg.TenantID,
		arg.Name,
		arg.StartDate,
		arg.EndDate,
		arg.Location,
	)
	var i Tournament
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.Name,
		&i.StartDate,
		&i.EndDate,
		&i.Location,
	)
	return i, err
}

const deleteTournament = `-- name: DeleteTournament :exec
DELETE FROM tournaments
WHERE id = $1 AND tenant_id = $2
`

type DeleteTournamentParams struct {
	ID       int32     `json:"id"`
	TenantID uuid.UUID `json:"tenant_id"`
}

func (q *Queries) DeleteTournament(ctx context.Context, arg DeleteTournamentParams) error {
	_, err := q.db.Exec(ctx, deleteTournament, arg.ID, arg.TenantID)
	return err
}

const getTournament = `-- name: GetTournament :one
SELECT id, tenant_id, name, start_date, end_date, location FROM tournaments
WHERE id = $1 AND tenant_id = $2
`

type GetTournamentParams struct {
	ID       int32     `json:"id"`
	TenantID uuid.UUID `json:"tenant_id"`
}

func (q *Queries) GetTournament(ctx context.Context, arg GetTournamentParams) (Tournament, error) {
	row := q.db.QueryRow(ctx, getTournament, arg.ID, arg.TenantID)
	var i Tournament
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.Name,
		&i.StartDate,
		&i.EndDate,
		&i.Location,
	)
	return i, err
}

const listTournaments = `-- name: ListTournaments :many
SELECT id, tenant_id, name, start_date, end_date, location FROM tournaments
WHERE tenant_id = $1
ORDER BY start_date DESC
`

func (q *Queries) ListTournaments(ctx context.Context, tenantID uuid.UUID) ([]Tournament, error) {
	rows, err := q.db.Query(ctx, listTournaments, tenantID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Tournament{}
	for rows.Next() {
		var i Tournament
		if err := rows.Scan(
			&i.ID,
			&i.TenantID,
			&i.Name,
			&i.StartDate,
			&i.EndDate,
			&i.Location,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listTournamentsByDateRange = `-- name: ListTournamentsByDateRange :many
SELECT id, tenant_id, name, start_date, end_date, location FROM tournaments
WHERE tenant_id = $1
  AND start_date >= $2
  AND end_date <= $3
ORDER BY start_date DESC
`

type ListTournamentsByDateRangeParams struct {
	TenantID  uuid.UUID   `json:"tenant_id"`
	StartDate pgtype.Date `json:"start_date"`
	EndDate   pgtype.Date `json:"end_date"`
}

func (q *Queries) ListTournamentsByDateRange(ctx context.Context, arg ListTournamentsByDateRangeParams) ([]Tournament, error) {
	rows, err := q.db.Query(ctx, listTournamentsByDateRange, arg.TenantID, arg.StartDate, arg.EndDate)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Tournament{}
	for rows.Next() {
		var i Tournament
		if err := rows.Scan(
			&i.ID,
			&i.TenantID,
			&i.Name,
			&i.StartDate,
			&i.EndDate,
			&i.Location,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateTournament = `-- name: UpdateTournament :one
UPDATE tournaments
SET
    name = $3,
    start_date = $4,
    end_date = $5,
    location = $6
WHERE id = $1 AND tenant_id = $2
RETURNING id, tenant_id, name, start_date, end_date, location
`

type UpdateTournamentParams struct {
	ID        int32       `json:"id"`
	TenantID  uuid.UUID   `json:"tenant_id"`
	Name      string      `json:"name"`
	StartDate pgtype.Date `json:"start_date"`
	EndDate   pgtype.Date `json:"end_date"`
	Location  string      `json:"location"`
}

func (q *Queries) UpdateTournament(ctx context.Context, arg UpdateTournamentParams) (Tournament, error) {
	row := q.db.QueryRow(ctx, updateTournament,
		arg.ID,
		arg.TenantID,
		arg.Name,
		arg.StartDate,
		arg.EndDate,
		arg.Location,
	)
	var i Tournament
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.Name,
		&i.StartDate,
		&i.EndDate,
		&i.Location,
	)
	return i, err
}
