// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: tournament_players.sql

package sqlc

import (
	"context"
	"time"

	"github.com/google/uuid"
)

const createTournamentPlayer = `-- name: CreateTournamentPlayer :one

WITH ins AS (
    INSERT INTO tournament_players (tournament_id, player_id, tenant_id, tier, biography, hdcp)
    VALUES ($1, $2, $3, $4, $5, $6)
    RETURNING tournament_id, player_id, tenant_id, tier, biography, hdcp, created_at, updated_at
)
SELECT ins.tournament_id, ins.player_id, ins.tenant_id, ins.tier, ins.biography, ins.hdcp, ins.created_at, ins.updated_at, p.first_name, p.last_name, p.photo_path, tm.team_id
FROM ins
JOIN players p ON ins.player_id = p.id
LEFT JOIN team_members tm ON tm.tournament_id = ins.tournament_id AND tm.player_id = ins.player_id
`

type CreateTournamentPlayerParams struct {
	TournamentID uuid.UUID `json:"tournament_id"`
	PlayerID     uuid.UUID `json:"player_id"`
	TenantID     uuid.UUID `json:"tenant_id"`
	Tier         string    `json:"tier"`
	Biography    string    `json:"biography"`
	Hdcp         float32   `json:"hdcp"`
}

type CreateTournamentPlayerRow struct {
	TournamentID uuid.UUID  `json:"tournament_id"`
	PlayerID     uuid.UUID  `json:"player_id"`
	TenantID     uuid.UUID  `json:"tenant_id"`
	Tier         string     `json:"tier"`
	Biography    string     `json:"biography"`
	Hdcp         float32    `json:"hdcp"`
	CreatedAt    time.Time  `json:"created_at"`
	UpdatedAt    time.Time  `json:"updated_at"`
	FirstName    string     `json:"first_name"`
	LastName     string     `json:"last_name"`
	PhotoPath    string     `json:"photo_path"`
	TeamID       *uuid.UUID `json:"team_id"`
}

// tournament_players holds a player's per-tournament attributes (tier, biography,
// handicap), set independently of the team draft. All reads/writes return the same
// enriched shape: the entry plus the player's identity and team assignment (team_id
// NULL when entered but undrafted).
// CreateTournamentPlayer inserts the entry and returns it enriched with identity/team.
func (q *Queries) CreateTournamentPlayer(ctx context.Context, arg CreateTournamentPlayerParams) (CreateTournamentPlayerRow, error) {
	row := q.db.QueryRow(ctx, createTournamentPlayer,
		arg.TournamentID,
		arg.PlayerID,
		arg.TenantID,
		arg.Tier,
		arg.Biography,
		arg.Hdcp,
	)
	var i CreateTournamentPlayerRow
	err := row.Scan(
		&i.TournamentID,
		&i.PlayerID,
		&i.TenantID,
		&i.Tier,
		&i.Biography,
		&i.Hdcp,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.FirstName,
		&i.LastName,
		&i.PhotoPath,
		&i.TeamID,
	)
	return i, err
}

const getTournamentPlayer = `-- name: GetTournamentPlayer :one
SELECT tp.tournament_id, tp.player_id, tp.tenant_id, tp.tier, tp.biography, tp.hdcp, tp.created_at, tp.updated_at, p.first_name, p.last_name, p.photo_path, tm.team_id
FROM tournament_players tp
JOIN players p ON tp.player_id = p.id
LEFT JOIN team_members tm ON tm.tournament_id = tp.tournament_id AND tm.player_id = tp.player_id
WHERE tp.tournament_id = $1 AND tp.player_id = $2 AND tp.tenant_id = $3
`

type GetTournamentPlayerParams struct {
	TournamentID uuid.UUID `json:"tournament_id"`
	PlayerID     uuid.UUID `json:"player_id"`
	TenantID     uuid.UUID `json:"tenant_id"`
}

type GetTournamentPlayerRow struct {
	TournamentID uuid.UUID  `json:"tournament_id"`
	PlayerID     uuid.UUID  `json:"player_id"`
	TenantID     uuid.UUID  `json:"tenant_id"`
	Tier         string     `json:"tier"`
	Biography    string     `json:"biography"`
	Hdcp         float32    `json:"hdcp"`
	CreatedAt    time.Time  `json:"created_at"`
	UpdatedAt    time.Time  `json:"updated_at"`
	FirstName    string     `json:"first_name"`
	LastName     string     `json:"last_name"`
	PhotoPath    string     `json:"photo_path"`
	TeamID       *uuid.UUID `json:"team_id"`
}

// GetTournamentPlayer returns one entered player, enriched the same way the list is.
func (q *Queries) GetTournamentPlayer(ctx context.Context, arg GetTournamentPlayerParams) (GetTournamentPlayerRow, error) {
	row := q.db.QueryRow(ctx, getTournamentPlayer, arg.TournamentID, arg.PlayerID, arg.TenantID)
	var i GetTournamentPlayerRow
	err := row.Scan(
		&i.TournamentID,
		&i.PlayerID,
		&i.TenantID,
		&i.Tier,
		&i.Biography,
		&i.Hdcp,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.FirstName,
		&i.LastName,
		&i.PhotoPath,
		&i.TeamID,
	)
	return i, err
}

const listPlayerTournaments = `-- name: ListPlayerTournaments :many
SELECT
    t.id AS tournament_id,
    t.name,
    t.location,
    t.start_date,
    t.end_date,
    cap.first_name AS captain_first_name,
    cap.last_name  AS captain_last_name,
    tm.team_id,
    tp.tier,
    tp.biography,
    COUNT(*) FILTER (WHERE o.won) AS wins,
    COUNT(*) FILTER (WHERE o.lost) AS losses,
    COUNT(*) FILTER (WHERE o.tied) AS ties
FROM tournament_players tp
JOIN tournaments t ON t.id = tp.tournament_id AND t.tenant_id = tp.tenant_id
LEFT JOIN team_members tm ON tm.tournament_id = tp.tournament_id AND tm.player_id = tp.player_id AND tm.tenant_id = tp.tenant_id
LEFT JOIN teams te ON te.id = tm.team_id AND te.tenant_id = tm.tenant_id
LEFT JOIN players cap ON cap.id = te.captain_id AND cap.tenant_id = te.tenant_id
LEFT JOIN player_match_outcomes o ON o.player_id = tp.player_id AND o.tournament_id = tp.tournament_id AND o.tenant_id = tp.tenant_id
WHERE tp.player_id = $1 AND tp.tenant_id = $2
GROUP BY t.id, t.name, t.location, t.start_date, t.end_date, tm.team_id, cap.first_name, cap.last_name, tp.tier, tp.biography
ORDER BY t.start_date DESC
`

type ListPlayerTournamentsParams struct {
	PlayerID uuid.UUID `json:"player_id"`
	TenantID uuid.UUID `json:"tenant_id"`
}

type ListPlayerTournamentsRow struct {
	TournamentID     uuid.UUID  `json:"tournament_id"`
	Name             string     `json:"name"`
	Location         string     `json:"location"`
	StartDate        time.Time  `json:"start_date"`
	EndDate          time.Time  `json:"end_date"`
	CaptainFirstName *string    `json:"captain_first_name"`
	CaptainLastName  *string    `json:"captain_last_name"`
	TeamID           *uuid.UUID `json:"team_id"`
	Tier             string     `json:"tier"`
	Biography        string     `json:"biography"`
	Wins             int64      `json:"wins"`
	Losses           int64      `json:"losses"`
	Ties             int64      `json:"ties"`
}

// A player's tournament history: their side that year (via its captain) and their
// per-tournament W-L-T. The verdict for that side is derived in the domain from the
// returned team_id. LEFT JOINs throughout, since a player can be entered but undrafted.
func (q *Queries) ListPlayerTournaments(ctx context.Context, arg ListPlayerTournamentsParams) ([]ListPlayerTournamentsRow, error) {
	rows, err := q.db.Query(ctx, listPlayerTournaments, arg.PlayerID, arg.TenantID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListPlayerTournamentsRow{}
	for rows.Next() {
		var i ListPlayerTournamentsRow
		if err := rows.Scan(
			&i.TournamentID,
			&i.Name,
			&i.Location,
			&i.StartDate,
			&i.EndDate,
			&i.CaptainFirstName,
			&i.CaptainLastName,
			&i.TeamID,
			&i.Tier,
			&i.Biography,
			&i.Wins,
			&i.Losses,
			&i.Ties,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listTournamentPlayers = `-- name: ListTournamentPlayers :many
SELECT tp.tournament_id, tp.player_id, tp.tenant_id, tp.tier, tp.biography, tp.hdcp, tp.created_at, tp.updated_at, p.first_name, p.last_name, p.photo_path, tm.team_id
FROM tournament_players tp
JOIN players p ON tp.player_id = p.id
LEFT JOIN team_members tm ON tm.tournament_id = tp.tournament_id AND tm.player_id = tp.player_id
WHERE tp.tournament_id = $1 AND tp.tenant_id = $2
ORDER BY p.last_name, p.first_name
`

type ListTournamentPlayersParams struct {
	TournamentID uuid.UUID `json:"tournament_id"`
	TenantID     uuid.UUID `json:"tenant_id"`
}

type ListTournamentPlayersRow struct {
	TournamentID uuid.UUID  `json:"tournament_id"`
	PlayerID     uuid.UUID  `json:"player_id"`
	TenantID     uuid.UUID  `json:"tenant_id"`
	Tier         string     `json:"tier"`
	Biography    string     `json:"biography"`
	Hdcp         float32    `json:"hdcp"`
	CreatedAt    time.Time  `json:"created_at"`
	UpdatedAt    time.Time  `json:"updated_at"`
	FirstName    string     `json:"first_name"`
	LastName     string     `json:"last_name"`
	PhotoPath    string     `json:"photo_path"`
	TeamID       *uuid.UUID `json:"team_id"`
}

// ListTournamentPlayers returns every entered player, enriched.
func (q *Queries) ListTournamentPlayers(ctx context.Context, arg ListTournamentPlayersParams) ([]ListTournamentPlayersRow, error) {
	rows, err := q.db.Query(ctx, listTournamentPlayers, arg.TournamentID, arg.TenantID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListTournamentPlayersRow{}
	for rows.Next() {
		var i ListTournamentPlayersRow
		if err := rows.Scan(
			&i.TournamentID,
			&i.PlayerID,
			&i.TenantID,
			&i.Tier,
			&i.Biography,
			&i.Hdcp,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.FirstName,
			&i.LastName,
			&i.PhotoPath,
			&i.TeamID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listTournamentPlayersByTeam = `-- name: ListTournamentPlayersByTeam :many
SELECT tp.tournament_id, tp.player_id, tp.tenant_id, tp.tier, tp.biography, tp.hdcp, tp.created_at, tp.updated_at, p.first_name, p.last_name, p.photo_path, tm.team_id
FROM tournament_players tp
JOIN players p ON tp.player_id = p.id
JOIN team_members tm ON tm.tournament_id = tp.tournament_id AND tm.player_id = tp.player_id
WHERE tm.team_id = $1 AND tp.tenant_id = $2
ORDER BY p.last_name, p.first_name
`

type ListTournamentPlayersByTeamParams struct {
	TeamID   uuid.UUID `json:"team_id"`
	TenantID uuid.UUID `json:"tenant_id"`
}

type ListTournamentPlayersByTeamRow struct {
	TournamentID uuid.UUID `json:"tournament_id"`
	PlayerID     uuid.UUID `json:"player_id"`
	TenantID     uuid.UUID `json:"tenant_id"`
	Tier         string    `json:"tier"`
	Biography    string    `json:"biography"`
	Hdcp         float32   `json:"hdcp"`
	CreatedAt    time.Time `json:"created_at"`
	UpdatedAt    time.Time `json:"updated_at"`
	FirstName    string    `json:"first_name"`
	LastName     string    `json:"last_name"`
	PhotoPath    string    `json:"photo_path"`
	TeamID       uuid.UUID `json:"team_id"`
}

// ListTournamentPlayersByTeam returns the same rows filtered to one team's drafted
// players.
func (q *Queries) ListTournamentPlayersByTeam(ctx context.Context, arg ListTournamentPlayersByTeamParams) ([]ListTournamentPlayersByTeamRow, error) {
	rows, err := q.db.Query(ctx, listTournamentPlayersByTeam, arg.TeamID, arg.TenantID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListTournamentPlayersByTeamRow{}
	for rows.Next() {
		var i ListTournamentPlayersByTeamRow
		if err := rows.Scan(
			&i.TournamentID,
			&i.PlayerID,
			&i.TenantID,
			&i.Tier,
			&i.Biography,
			&i.Hdcp,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.FirstName,
			&i.LastName,
			&i.PhotoPath,
			&i.TeamID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateTournamentPlayer = `-- name: UpdateTournamentPlayer :one
UPDATE tournament_players
SET tier = COALESCE($1, tier),
    biography = COALESCE($2, biography),
    hdcp = COALESCE($3, hdcp),
    updated_at = now()
WHERE tournament_id = $4
  AND player_id = $5
  AND tenant_id = $6
RETURNING player_id
`

type UpdateTournamentPlayerParams struct {
	Tier         *string   `json:"tier"`
	Biography    *string   `json:"biography"`
	Hdcp         *float32  `json:"hdcp"`
	TournamentID uuid.UUID `json:"tournament_id"`
	PlayerID     uuid.UUID `json:"player_id"`
	TenantID     uuid.UUID `json:"tenant_id"`
}

// UpdateTournamentPlayer writes only the attributes that were supplied: a null argument
// leaves the column alone, so setting a biography never has to restate the tier and
// handicap. Most entries carry a handicap, and echoing one back is how it gets lost.
//
// Separate from the enriched read below rather than one CTE, because sqlc cannot analyse
// an UPDATE inside a CTE once its SET clause references the columns it is updating. The
// repository runs both in a single transaction, so this costs a statement, not a trip.
func (q *Queries) UpdateTournamentPlayer(ctx context.Context, arg UpdateTournamentPlayerParams) (uuid.UUID, error) {
	row := q.db.QueryRow(ctx, updateTournamentPlayer,
		arg.Tier,
		arg.Biography,
		arg.Hdcp,
		arg.TournamentID,
		arg.PlayerID,
		arg.TenantID,
	)
	var player_id uuid.UUID
	err := row.Scan(&player_id)
	return player_id, err
}
